---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rook-ceph-csi
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - chart: ceph-csi-drivers
      repoURL: https://ceph.github.io/ceph-csi-operator
      targetRevision: 1.0.4
      helm:
        valueFiles:
          - $values/clusters/k8s-01/apps/rook/csi/values.yaml
    - repoURL: 'https://github.com/synthe102/homelab.git'
      targetRevision: HEAD
      ref: values
  destination:
    name: in-cluster
    namespace: rook-ceph
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
