config:
  bookmarks:
    - Developer:
        - Github:
            - abbr: GH
              href: https://github.com/
  widgets:
    # show the kubernetes widget, with the cluster summary and individual nodes
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "cluster"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
  kubernetes:
    mode: cluster
  settings:

# The service account is necessary to allow discovery of other services
serviceAccount:
  create: true
  name: homepage

# This enables the service account to access the necessary resources
enableRbac: true

ingress:
  main:
    enabled: true
    className: "cilium"
    annotations:
      kubernetes.io/ingress.class: cilium
      cert-manager.io/cluster-issuer: letsencrypt-prod
    hosts:
      - host: &host homepage.suslian.engineer
        paths:
          - path: /
    tls:
      - hosts:
          - *host
        secretName: homepage-tls
