apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: velero-creds
  namespace: velero
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-auth-api
  target:
    name: velero-creds
    template:
      engineVersion: v2
      data:
        config: |
          [default]
          aws_access_key_id={{ .AWS_ACCESS_KEY_ID }}
          aws_secret_access_key={{ .AWS_SECRET_ACCESS_KEY }}
          region=eu-west-1
  data:
  - secretKey: AWS_ACCESS_KEY_ID
    remoteRef:
      key: VELERO_ACCESS_KEY_ID
  - secretKey: AWS_SECRET_ACCESS_KEY
    remoteRef:
      key: VELERO_SECRET_ACCESS_KEY
