configuration:
  uploaderType: kopia
  backupStorageLocation:
    - bucket: "velero-backups-synthe"
      defaultVolumesToFsBackup: False
      provider: aws
      config:
        region: eu-west-1
  volumeSnapshotLocation:
    - provider: aws
      config:
        region: eu-west-1
initContainers:
  - name: velero-plugin-for-aws
    image: velero/velero-plugin-for-aws:v1.10.0
    imagePullPolicy: IfNotPresent
    volumeMounts:
      - mountPath: /target
        name: plugins
deployNodeAgent: true
features: EnableCSI  
credentials:
  existingSecret: velero-creds
