configuration:
  features: EnableCSI
  backupStorageLocation:
    - bucket: "velero-backups-synthe"
      provider: aws
      config:
        region: eu-west-1
  volumeSnapshotLocation:
    - provider: aws
      config:
        region: eu-west-1
initContainers:
  - name: velero-plugin-for-aws
    image: velero/velero-plugin-for-aws:v1.12.1
    imagePullPolicy: IfNotPresent
    volumeMounts:
      - mountPath: /target
        name: plugins
deployNodeAgent: true
credentials:
  existingSecret: velero-creds
