apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: velero-creds
  namespace: velero
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-auth-api
  target:
    name: velero-creds
    template:
      engineVersion: v2
      data:
        cloud: |
          [default]
          aws_access_key_id={{ .AWS_ACCESS_KEY_ID }}
          aws_secret_access_key={{ .AWS_SECRET_ACCESS_KEY }}
          region=eu-west-1
  data:
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: VELERO_ACCESS_KEY_ID
        metadataPolicy: None
      secretKey: AWS_ACCESS_KEY_ID
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: VELERO_SECRET_ACCESS_KEY
        metadataPolicy: None
      secretKey: AWS_SECRET_ACCESS_KEY
