---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: buildkitd
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - path: clusters/k8s-01/apps/github-actions/buildkitd/configs
      repoURL: 'https://github.com/synthe102/homelab.git'
      targetRevision: HEAD
  destination:
    name: in-cluster
    namespace: arc-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
