apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: daily-global
  namespace: velero-system
spec:
  schedule: '0 2 * * *'
  template:
    snapshotMoveData: true
    excludedNamespaces:
    - 'vcluster-*'
    - 'monitoring'
    - 'velero-system'
    # 30 days retention
    ttl: 720h0m0s
