---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openbao
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - chart: openbao
      repoURL: https://openbao.github.io/openbao-helm
      targetRevision: 0.29.4
      helm:
        valueFiles:
          - $values/clusters/k8s-01/apps/security/openbao/values.yaml
    - path: clusters/k8s-01/apps/security/openbao/configs
      repoURL: 'https://github.com/synthe102/homelab.git'
      targetRevision: HEAD
    - repoURL: 'https://github.com/synthe102/homelab.git'
      targetRevision: HEAD
      ref: values
  destination:
    name: in-cluster
    namespace: openbao
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
