---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns-unifi
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: 'https://github.com/synthe102/homelab.git'
      targetRevision: HEAD
      ref: values
    - chart: external-dns
      repoURL: https://kubernetes-sigs.github.io/external-dns/
      targetRevision: 1.20.0
      helm:
        valueFiles:
          - $values/clusters/k8s-01/apps/external-dns/unifi/values.yaml
    - path: clusters/k8s-01/apps/external-dns/unifi/configs
      repoURL: 'https://github.com/synthe102/homelab.git'
      targetRevision: HEAD
  destination:
    name: in-cluster
    namespace: external-dns
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
