---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dp-operator
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - chart: intel-device-plugins-operator
      repoURL: https://intel.github.io/helm-charts
      targetRevision: 0.36.0
      helm:
        valueFiles:
          - $values/clusters/k8s-01/apps/kube-system/intel-device-plugin/operator/values.yaml
    - repoURL: 'https://github.com/synthe102/homelab.git'
      targetRevision: HEAD
      ref: values
  destination:
    name: in-cluster
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
