apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns-pihole
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: in-cluster
    namespace: external-dns-pihole
  project: default
  sources:
  - chart: external-dns
    helm:
      valueFiles:
      - $values/k8s/sources/external-dns-pihole/values.yaml
    repoURL: https://kubernetes-sigs.github.io/external-dns
    targetRevision: 1.14.*
  - ref: values
    repoURL: https://github.com/synthe102/homelab.git
    targetRevision: main
  syncPolicy:
    syncOptions:
    - PruneLast=true
    - CreateNamespace=true
    - ServerSideApply=true
