---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: open-webui
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: in-cluster
    namespace: inference
  project: default
  sources:
    - repoURL: https://open-webui.github.io/helm-charts
      targetRevision: 6.19.0
      chart: open-webui
      helm:
        valuesObject:
          ollama:
            enabled: false
          ollamaUrls:
            - http://ollama:11434
          ingress:
            enabled: true
            class: kong
            host: chat.suslian.engineer
            annotations:
              cert-manager.io/cluster-issuer: letsencrypt-prod
              konghq.com/https-redirect-status-code: "301"
            tls: true
          persistence:
            size: 10Gi
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
