apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: &name postgres
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
  - path: clusters/k8s-01/apps/databases/postgres/configs
    repoURL: 'https://github.com/synthe102/homelab.git'
    targetRevision: HEAD
  destination:
    name: in-cluster
    namespace: databases
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
