vault:
  server:
    dev:
      enabled: true
    ingress:
      enabled: false
      annotations:
        kubernetes.io/ingress.class: nginx
        external-dns.alpha.kubernetes.io/target: "homelab-direct.suslian.engineer"
        cert-manager.io/cluster-issuer: letsencrypt-staging
      hosts:
        - host: vault.suslian.engineer
      tls:
        - secretName: vault-tls-secret #Do not change, required by argo-cd
          hosts:
            - vault.suslian.engineer
