controllers:
  main:
    pod:
      securityContext:
        fsGroup: 568
        fsGroupChangePolicy: "OnRootMismatch"

    containers:
      main:
        nameOverride: jellyseerr
        image:
          repository: fallenbagel/jellyseerr
          tag: 1.9.0
        env:
          UMASK: "022"
          TZ: "Europe/Paris"
        securityContext:
          runAsUser: 568
          runAsGroup: 568

service:
  main:
    ports:
      http:
        port: 5055

ingress:
  main:
    enabled: true
    className: "kong"
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      konghq.com/protocols: https
      konghq.com/https-redirect-status-code: "301"
    hosts:
      - host: &host1 requests.suslian.engineer
        paths:
          - path: /
            service:
              name: main
              port: http
      - host: &host2 tv-shows.suslian.engineer
        paths:
          - path: /
            service:
              name: main
              port: http
      - host: &host3 movies.suslian.engineer
        paths:
          - path: /
            service:
              name: main
              port: http
    tls:
      - hosts:
          - *host1
          - *host2
          - *host3
        secretName: jellyseerr-tls

persistence:
  config:
    enabled: true
    type: persistentVolumeClaim
    accessMode: ReadWriteOnce
    size: 5Gi
    advancedMounts:
      main:
        main:
          - path: /app/config
