---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sr-iov
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: 'https://github.com/synthe102/homelab.git'
      targetRevision: HEAD
      ref: values
    - chart: sriov-network-operator-chart
      repoURL: ghcr.io/k8snetworkplumbingwg
      targetRevision: 1.6.0
      helm:
        valueFiles:
          - $values/clusters/k8s-01/apps/kube-system/sr-iov/values.yaml
  destination:
    name: in-cluster
    namespace: kube-system
  # syncPolicy:
  #   automated:
  #     prune: true
  #     selfHeal: true
