---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sr-iov
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - chart: sriov-network-operator-chart
      repoURL: ghcr.io/k8snetworkplumbingwg
      targetRevision: 1.5.0
      helm:
        valuesObject:
          sriovOperatorConfig:
            deploy: true
            configDaemonNodeSelector:
              feature.node.kubernetes.io/network-sriov.capable: "true"
  destination:
    name: in-cluster
    namespace: kube-system
  # syncPolicy:
  #   automated:
  #     prune: true
  #     selfHeal: true
