---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: openbao-unseal
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-homelab
    kind: ClusterSecretStore
  data:
    - secretKey: key
      remoteRef:
        key: "K8S_01_KUBE_OPENBAO_UNSEAL_KEY"
