kong:
  image:
  repository: kong
  tag: "2.8"

  env:
    prefix: /kong_prefix/
    database: "off"

  ingressController:
    enabled: true
  certificates:
    enabled: true
    clusterIssuer: letsencrypt-prod
    admin:
      enabled: false
    cluster:
      enabled: false
    proxy:
      enabled: true
      clusterIssuer: letsencrypt-prod
      commonName: suslian.engineer
      dnsNames:
        - "suslian.engineer"
        - "*.suslian.engineer"
