---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8s-monitoring
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: k8s-monitoring
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 3.5.5
    helm:
      valuesObject:
        cluster:
          name: k8s-01
        alloy-singleton:
          enabled: true
          extraConfig: |-
            mimir.rules.kubernetes "default" {
              address = "http://mimir-ruler.monitoring.svc:8080"
              tenant_id = "anonymous"
            }
        alloy-logs:
          enabled: true
        alloy-metrics:
          enabled: true
        alloy-profiles:
          enabled: true
        destinations:
          - name: logs
            type: loki
            url: http://loki-headless.monitoring.svc.cluster.local:3100/loki/api/v1/push
          - name: metrics
            type: prometheus
            url: http://mimir-nginx.monitoring.svc.cluster.local:80/api/v1/push
          - name: profiles
            type: pyroscope
            url: http://pyroscope-headless.monitoring.svc.cluster.local:4040
        clusterMetrics:
          enabled: true
          node-exporter:
            deploy: false
        prometheusOperatorObjects:
          enabled: true
        clusterEvents:
          enabled: true
        podLogs:
          enabled: true
        profiling:
          enabled: true
  destination:
    name: in-cluster
    namespace: monitoring
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
