---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8s-monitoring
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: 'https://github.com/synthe102/homelab.git'
      targetRevision: HEAD
      ref: values
    - chart: k8s-monitoring
      repoURL: https://grafana.github.io/helm-charts
      targetRevision: 3.7.1
      helm:
        valueFiles:
          - $values/clusters/k8s-01/apps/monitoring/k8s-monitoring/values.yaml
  destination:
    name: in-cluster
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
