---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8s-monitoring
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: k8s-monitoring
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 3.6.2
    helm:
      valuesObject:
        cluster:
          name: k8s-01
        alloy-singleton:
          enabled: true
          alloy:
            stabilityLevel: experimental
          extraConfig: |-
            mimir.rules.kubernetes "default" {
              address = "http://mimir-ruler.monitoring.svc:8080"
              tenant_id = "anonymous"
            }

            remote.kubernetes.configmap "default" {
              namespace = "monitoring"
              name      = "alertmgr-global"
            }

            mimir.alerts.kubernetes "default" {
              address = "http://mimir-ruler.monitoring.svc:8080"
              global_config = remote.kubernetes.configmap.default.data["glbl"]
              alertmanagerconfig_selector  {
                match_labels = {}
              }
            }
        alloy-logs:
          enabled: true
        alloy-metrics:
          enabled: true
        alloy-profiles:
          enabled: true
        destinations:
          - name: logs
            type: loki
            url: http://loki-headless.monitoring.svc.cluster.local:3100/loki/api/v1/push
          - name: metrics
            type: prometheus
            url: http://mimir-gateway.monitoring.svc.cluster.local:80/api/v1/push
          - name: profiles
            type: pyroscope
            url: http://pyroscope-headless.monitoring.svc.cluster.local:4040
        clusterMetrics:
          enabled: true
          node-exporter:
            deploy: true
            prometheus:
              podMonitor:
                enabled: true
          kube-state-metrics:
            deploy: true
            prometheus:
              monitor:
                enabled: true
        prometheusOperatorObjects:
          enabled: true
        clusterEvents:
          enabled: true
        podLogs:
          enabled: true
        profiling:
          enabled: true
  destination:
    name: in-cluster
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
