controllers:
  main:
    containers:
      main:
        nameOverride: protonmail-bridge
        image:
          repository: shenxn/protonmail-bridge
          tag: 3.7.1-1

service:
  main:
    ports:
      http:
        enabled: false
      smtp:
        port: 25

persistence:
  root:
    enabled: true
    type: persistentVolumeClaim
    accessMode: ReadWriteOnce
    size: 5Gi
