apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd
  namespace: argocd
spec:
  project: default
  source:
    chart: argo-cd
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: 7.8.10
    helm:
      valuesObject:
        redis-ha:
          enabled: true
        controller:
          replicas: 1
        repoServer:
          replicas: 2
        applicationSet:
          replicas: 2
        server:
          replicas: 2
          service:
            annotations:
              konghq.com/protocol: https
          ingress:
            enabled: true
            ingressClassName: "kong"
            annotations:
              cert-manager.io/cluster-issuer: letsencrypt-prod
              konghq.com/protocols: "https,grpcs"
              konghq.com/https-redirect-status-code: "301"
            tls: true
            hostname: argo.k8s-01.suslian.engineer
  destination:
    name: in-cluster
    namespace: argocd
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
