---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minecraft-volcan
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: in-cluster
    namespace: game-servers
  project: default
  sources:
    - chart: app-template
      helm:
        valuesObject:
          defaultPodOptions:
            imagePullSecrets:
              - name: ghcr-synthe102
          controllers:
            main:
              replicas: 1
              annotations:
                reloader.stakater.com/auto: "true"
              pod:
                securityContext:
                  fsGroup: 568
                  fsGroupChangePolicy: "OnRootMismatch"
              containers:
                main:
                  nameOverride: minecraft-server
                  image:
                    repository: ghcr.io/itzg/minecraft-server
                    tag: 2025.10.2-java21
                  env:
                    EULA: "true"
                    TZ: "Europe/Paris"
                    ENABLE_ROLLING_LOGS: "true"
                    SERVER_NAME: "Volcan"
                    MOTD: "Le serveur volcanique"
                    ICON: "https://media.discordapp.net/attachments/860158395628650537/955376790543691816/Untitled-1-01.png?ex=68f9e1f8&is=68f89078&hm=49650956e6ae5ae9343391bf5464f27f6d6d1a7c4f2daaa0c1b12f98a1212006&=&format=webp&quality=lossless&width=1296&height=1296"
                    MEMORY: 4G
                    INIT_MEMORY: 1G
                    MAX_MEMORY: 4G
                    ONLINE_MODE: "true"
                    TYPE: PAPER
                    PAPER_BUILD: 60
                    VERSION: "1.21.8"
                    MODRINTH_PROJECTS: "directionhud,viaversion,tab-was-taken,chunky"
                    MODRINTH_ALLOWED_VERSION_TYPE: "beta"
                  envFrom:
                    - secretRef:
                        name: minecraft-volcan
                  resources:
                    requests:
                      cpu: 1
                      memory: 5Gi
                    limits:
                      memory: 5Gi
                  securityContext:
                    runAsNonRoot: true
                    runAsUser: 568
                    runAsGroup: 568
                    allowPrivilegeEscalation: false
                    readOnlyRootFilesystem: true
                    capabilities: {drop: ["ALL"]}
                  tty: true
                  stdin: true
                  # volcan:
                  #   nameOverride: volcan-bot
                  #   image:
                  #     repository: ghcr.io/synthe102/volcan-bot
                  #     tag: "v0.0.3"
                  #   env:
                  #     MINECRAFT_RCON_ADDRESS: localhost:25575
                  #     MINECRAFT_WHITELIST_FILE: /data/whitelist.json
                  #     SQLITE_DATABASE: /data/volcan.db
                  #   envFrom:
                  #     - secretRef:
                  #         name: minecraft-volcan
          service:
            main:
              type: LoadBalancer
              annotations:
                external-dns.alpha.kubernetes.io/hostname: mc.volcan.cloud
              controller: main
              ports:
                map:
                  port: 8123
                server:
                  port: 25565
                metrics:
                  port: 9100
          serviceMonitor:
            app:
              endpoints:
                - port: metrics
          route:
            main:
              hostnames:
                - "mc-map.volcan.cloud"
              parentRefs:
                - name: external
                  namespace: kube-system
                  sectionName: https-volcan
          persistence:
            data:
              enabled: true
              type: persistentVolumeClaim
              accessMode: ReadWriteOnce
              size: 35Gi
            tmp:
              enabled: true
              type: emptyDir
              sizeLimit: 512Mi
            dshm:
              enabled: true
              type: emptyDir
              sizeLimit: 512Mi
              globalMounts:
                - path: /dev/shm
      repoURL: https://bjw-s-labs.github.io/helm-charts
      targetRevision: 4.4.0
    - path: clusters/k8s-01/apps/game-servers/minecraft/configs
      repoURL: 'https://github.com/synthe102/homelab.git'
      targetRevision: HEAD
  syncPolicy:
    # automated:
    #   prune: true
    #   selfHeal: true
    syncOptions:
      - CreateNamespace=true
