---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minecraft-volcan
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: in-cluster
    namespace: game-servers
  project: default
  sources:
    - chart: app-template
      helm:
        valuesObject:
          controllers:
            main:
              type: statefulset
              pod:
                securityContext:
                  fsGroup: 568
                  fsGroupChangePolicy: "OnRootMismatch"
              containers:
                main:
                  nameOverride: minecraft-server
                  image:
                    repository: ghcr.io/itzg/minecraft-server
                    tag: java21@sha256:71f150e73832ad0b6a0ef23321b1d3fca4a1a6e59a41aaa514d25efc935b3614
                  env:
                    EULA: "true"
                    TZ: "Europe/Paris"
                    ENABLE_ROLLING_LOGS: "true"
                    SERVER_NAME: "Volcan"
                    MOTD: "Le serveur volcanique"
                    ICON: "https://media.discordapp.net/attachments/860158395628650537/955376790543691816/Untitled-1-01.png?ex=6878aef8&is=68775d78&hm=d28c9c93523409e3495e48aa1acab4ea2f1798d482cef04d199614e83d405637&=&quality=lossless&width=1296&height=1296"
                  envFrom:
                    - secretRef:
                        name: minecraft-volcan
                  securityContext:
                    runAsUser: 568
                    runAsGroup: 568
                  tty: true
                  stdin: true
          service:
            main:
              type: LoadBalancer
              annotations:
                external-dns.alpha.kubernetes.io/hostname: mc.volcan.cloud
              controller: main
              ports:
                http:
                  port: 25565
          persistence:
            data:
              enabled: true
              type: persistentVolumeClaim
              accessMode: ReadWriteOnce
              size: 10Gi
      repoURL: https://bjw-s-labs.github.io/helm-charts
      targetRevision: 4.1.2
    - path: clusters/k8s-01/apps/game-servers/minecraft/configs
      repoURL: 'https://github.com/synthe102/homelab.git'
      targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
