image:
  tag: 1.32.4
vaultwarden:
  admin:
    enabled: true
  log:
    level: warn
ingress:
  # -- Enables or disables the ingress
  enabled: true
  # -- Provide additional annotations which may be required.
  annotations:
    konghq.com/protocols: https
    konghq.com/https-redirect-status-code: "301"
    cert-manager.io/cluster-issuer: letsencrypt-prod
  # -- Set the ingressClass that is used for this ingress.
  # Requires Kubernetes >=1.19
  ingressClassName: "kong"
  ## Configure the hosts for the ingress
  host: vaultwarden.suslian.engineer
  # -- Configure TLS for the ingress. Both secretName and hosts can process a Helm template.
  tls: 
    - hosts:
        - vaultwarden.suslian.engineer
      secretName: vaultwarden-tls

serviceAccount:
  create: true

persistence:
  enabled: true
  size: 5Gi
