---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jellyfin
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - chart: app-template
      repoURL: https://bjw-s-labs.github.io/helm-charts
      targetRevision: 4.5.0
      helm:
        valuesObject:
          controllers:
            main:
              pod:
                securityContext:
                  fsGroup: 568
                  fsGroupChangePolicy: "OnRootMismatch"
              containers:
                main:
                  resources:
                    requests:
                      gpu.intel.com/i915: 1
                    limits:
                      gpu.intel.com/i915: 1
                  nameOverride: jellyfin
                  env:
                    UMASK: "022"
                    TZ: "Europe/Paris"
                  image:
                    repository: jellyfin/jellyfin
                    tag: 10.11.4
                  securityContext:
                    runAsUser: 568
                    runAsGroup: 568
          service:
            main:
              controller: main
              ports:
                http:
                  port: 8096
          persistence:
            config:
              suffix: config
              enabled: true
              type: persistentVolumeClaim
              accessMode: ReadWriteOnce
              size: 5Gi
            media:
              type: nfs
              server: 192.168.1.252
              path: /mnt/MainHDD/Media
          route:
            app:
              hostnames:
                - jellyfin.suslian.engineer
              parentRefs:
                - name: external
                  namespace: kube-system
                  sectionName: https
  destination:
    name: in-cluster
    namespace: media
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
