apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jellyfin
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
  - chart: app-template
    repoURL: https://bjw-s-labs.github.io/helm-charts
    targetRevision: 3.7.3
    helm:
      valuesObject:
        controllers:
          main:
            pod:
              securityContext:
                fsGroup: 568
                fsGroupChangePolicy: "OnRootMismatch"
            containers:
              main:
                resources:
                  requests:
                    gpu.intel.com/i915: 1
                  limits:
                    gpu.intel.com/i915: 1
                nameOverride: jellyfin
                env:
                  UMASK: "022"
                  TZ: "Europe/Paris"
                image:
                  repository: jellyfin/jellyfin
                  tag: 10.10.7
                securityContext:
                  runAsUser: 568
                  runAsGroup: 568
        service:
          main:
            controller: main
            ports:
              http:
                port: 8096
        ingress:
          main:
            enabled: true
            className: "kong"
            annotations:
              cert-manager.io/cluster-issuer: letsencrypt-prod
              konghq.com/protocols: https
              konghq.com/https-redirect-status-code: "301"
            hosts:
              - host: &host jellyfin.suslian.engineer
                paths:
                  - path: /
                    service:
                      identifier: main
                      port: http
            tls:
              - hosts:
                  - *host
                secretName: jellyfin-tls

        persistence:
          config:
            enabled: true
            type: persistentVolumeClaim
            accessMode: ReadWriteOnce
            size: 5Gi
          media:
            type: nfs
            server: 192.168.1.252
            path: /mnt/MainHDD/Media
  destination:
    name: in-cluster
    namespace: media
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
