ssh_authorized_keys:
- github:synthe102
hostname: nuc1
run_cmd:
- "sudo mount -t ext4 /dev/sda1 /var/lib/rancher/longhorn-sda"

k3os:
  token: homelab-cluster
  modules:
  - nvme
  k3s_args:
  - server
  - "--cluster-init"
  - "--disable-cloud-controller"
  - "--tls-san=homelab-cluster.suslian.engineer"
  - "--disable=servicelb"
  - "--disable=traefik"
  - "--disable=local-storage"
  - "--disable=metrics-server"