---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: zot
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: bitwarden-homelab
    kind: ClusterSecretStore
  target:
    name: zot
    template:
      engineVersion: v2
      data:
        config.json: |
          {
            "distSpecVersion": "1.1.0",
            "storage": {
              "rootDirectory": "/var/lib/registry",
              "gc": true,
              "dedupe": true
            },
            "http": {
              "address": "0.0.0.0",
              "port": "5000",
              "externalUrl": "https://registry.k8s-01.suslian.engineer",
              "auth": {
                "apikey": true,
                "openid": {
                  "providers": {
                    "oidc": {
                      "issuer": "https://auth.suslian.engineer/application/o/zot/",
                      "clientid": "{{ .oidcClientId }}",
                      "clientsecret": "{{ .oidcClientSecret }}",
                      "scopes": ["openid", "profile", "email", "groups"]
                    }
                  }
                }
              },
              "accessControl": {
                "repositories": {
                  "**": {
                    "anonymousPolicy": ["read"],
                    "defaultPolicy": ["read", "create", "update", "delete"]
                  }
                }
              }
            },
            "log": {
              "level": "info"
            },
            "extensions": {
              "ui": {"enable": true},
              "search": {"enable": true},
              "metrics": {"enable": true, "prometheus": {"path": "/metrics"}}
            }
          }
  dataFrom:
    - extract:
        key: K8S_01_REGISTRY_ZOT
