apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudnative-pg
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: in-cluster
    namespace: databases
  project: default
  sources:
  - chart: cloudnative-pg
    helm:
      valueFiles:
      - $values/k8s/sources/cnpg/values.yaml
    repoURL: https://cloudnative-pg.github.io/charts
    targetRevision: 0.20.*
  - ref: values
    repoURL: https://github.com/synthe102/homelab.git
    targetRevision: main
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
