---
# The Ceph-COSI driver needs a privileged user for each CephObjectStore
# in order to provision buckets and users
apiVersion: ceph.rook.io/v1
kind: CephObjectStoreUser
metadata:
  name: cosi
spec:
  displayName: "cosi user"
  store: ceph-objectstore
  capabilities:
    bucket: "*"
    user: "*"
