---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sriovdp-config
  namespace: kube-system
data:
  config.json: |
    {
      "resourceList": [
        {
          "resourceName": "x710",
          "resourcePrefix": "intel.com",
          "selectors": {
            "vendors": ["8086"],
            "drivers": ["iavf"],
            "pfNames": ["enp2s0f0np0"]
          }
        }
      ]
    }
