---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spegel
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: 'https://github.com/synthe102/homelab.git'
      targetRevision: HEAD
      ref: values
    - chart: spegel
      repoURL: ghcr.io/spegel-org/helm-charts
      targetRevision: 0.6.0
      helm:
        valueFiles:
          - $values/clusters/k8s-01/apps/kube-system/spegel/values.yaml
  destination:
    name: in-cluster
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
