apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spegel
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: spegel
    repoURL: ghcr.io/spegel-org/helm-charts
    targetRevision: 0.1.1
    helm:
      valuesObject:
        grafanaDashboard:
          enabled: true
        serviceMonitor:
          enabled: true
        spegel:
          prependExisting: true
          containerdSock: /run/containerd/containerd.sock
          containerdRegistryConfigPath: /etc/cri/conf.d/hosts
        service:
          registry:
            hostPort: 29999
  destination:
    name: in-cluster
    namespace: kube-system
