apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: &app system-upgrade-plan
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
  - path: clusters/k8s-01/apps/system-upgrade/plans/configs
    repoURL: 'https://github.com/synthe102/homelab.git'
    targetRevision: HEAD
  destination:
    name: in-cluster
    namespace: system-upgrade
