apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://raw.githubusercontent.com/k8snetworkplumbingwg/multus-cni/refs/tags/v4.2.0/deployments/multus-daemonset-thick.yml
  - serviceaccountsecret.yaml
images:
  - name: ghcr.io/k8snetworkplumbingwg/multus-cni
    newTag: v4.2.3-thick
patches:
  - path: patch.yaml
