apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kube-multus-ds
  namespace: kube-system
spec:
  template:
    spec:
      initContainers:
        - name: install-multus-binary
          command:
            - "/usr/src/multus-cni/bin/install_multus"
            - "-d"
            - "/host/opt/cni/bin"
            - "-t"
            - "thick"
        - command:
          - /install-cni.sh
          image: ghcr.io/siderolabs/install-cni:v1.9.0
          name: install-cni
          securityContext:
            privileged: true
          volumeMounts:
          - mountPath: /host/opt/cni/bin
            mountPropagation: Bidirectional
            name: cnibin
      volumes:
        - name: host-run-netns
          hostPath:
            path: /var/run/netns/
