---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - runtime-class.yaml
  - sandbox-router-deployment.yaml
  - sandbox-router-httproute.yaml
  - sandbox-router-service.yaml
