---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: sandbox-router
  namespace: agent-sandbox
spec:
  hostnames:
    - sandbox-router.k8s-01.suslian.engineer
  parentRefs:
    - name: internal
      namespace: kube-system
      sectionName: https-k8s-01
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: sandbox-router-svc
          port: 8080
