apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cnpg
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: cloudnative-pg
    repoURL: https://cloudnative-pg.github.io/charts
    targetRevision: 0.24.0
  destination:
    name: in-cluster
    namespace: cnpg-system
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
