---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lazylibrarian
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: in-cluster
    namespace: downloads
  project: default
  sources:
    - chart: app-template
      helm:
        valuesObject:
          controllers:
            main:
              pod:
                securityContext:
                  fsGroup: 568
                  fsGroupChangePolicy: "Always"
              containers:
                main:
                  nameOverride: lazylibrarian
                  image:
                    repository: lscr.io/linuxserver/lazylibrarian
                    tag: version-24e9733b
                  env:
                    UMASK: "022"
                    TZ: "Europe/Paris"
                    PGID: 568
                    PUID: 568
          service:
            main:
              controller: main
              ports:
                http:
                  port: 5299
          persistence:
            config:
              suffix: config
              enabled: true
              type: persistentVolumeClaim
              accessMode: ReadWriteOnce
              size: 5Gi
            media:
              type: nfs
              server: 192.168.1.252
              path: /mnt/MainHDD/Media
          route:
            app:
              hostnames:
                - lazylibrarian.suslian.engineer
              parentRefs:
                - name: internal
                  namespace: kube-system
                  sectionName: https
      repoURL: https://bjw-s-labs.github.io/helm-charts
      targetRevision: 4.6.2
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
