apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-configs
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: cert-manager
  project: default
  sources:
  - path: k8s/sources/cert-manager-configs
    repoURL: https://github.com/synthe102/homelab.git
    targetRevision: main
  syncPolicy:
    syncOptions:
    - PruneLast=true
    - CreateNamespace=true
    - ServerSideApply=true
