---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: &app smartctl-exporter
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: 'https://github.com/synthe102/homelab.git'
      targetRevision: HEAD
      ref: values
    - chart: prometheus-smartctl-exporter
      repoURL: https://prometheus-community.github.io/helm-charts
      targetRevision: 0.16.0
      helm:
        valueFiles:
          - $values/clusters/k8s-01/apps/monitoring/smartctl-exporter/values.yaml
  destination:
    name: in-cluster
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
