---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: projectsveltos
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: 'https://github.com/synthe102/homelab.git'
      targetRevision: HEAD
      ref: values
    - chart: projectsveltos
      repoURL: https://projectsveltos.github.io/helm-charts
      targetRevision: 1.3.3
      helm:
        valueFiles:
          - $values/clusters/k8s-01/apps/projectsveltos/values.yaml
  destination:
    name: in-cluster
    namespace: projectsveltos
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
