---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: projectsveltos
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - chart: projectsveltos
      repoURL: https://projectsveltos.github.io/helm-charts
      targetRevision: 1.1.2
      helm:
        valuesObject:
          agent:
            managementCluster: true
  destination:
    name: in-cluster
    namespace: projectsveltos
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
