---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/monitoring.coreos.com/alertmanagerconfig_v1alpha1.json
apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: alertmanager
spec:
  route:
    groupBy: ["alertname", "job"]
    groupInterval: 10m
    groupWait: 1m
    receiver: "null"
    repeatInterval: 12h
    routes:
      - receiver: telegram
        matchers:
          - name: severity
            value: critical
            matchType: =
  receivers:
  - name: "null"
  - name: telegram
    telegramConfigs:
      - botToken:
          name: telegram-bot-token
          key: bot-token
        chatID: -4797781084
        sendResolved: true
