---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - chart: loki
      repoURL: ghcr.io/grafana-community/helm-charts
      targetRevision: 18.12.0
      helm:
        valueFiles:
          - $values/clusters/k8s-01/apps/monitoring/loki/values.yaml
    - repoURL: 'https://github.com/synthe102/homelab.git'
      targetRevision: HEAD
      ref: values
  destination:
    name: in-cluster
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
