apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: qbittorrent
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: in-cluster
    namespace: downloads
  project: default
  sources:
  - chart: app-template
    helm:
      valuesObject:
        defaultPodOptions:
          annotations:
            k8s.v1.cni.cncf.io/networks: |
              [{
                "name": "multus-vpn-routed",
                "namespace": "kube-system",
                "ips": ["10.0.100.2/24"]
              }]
        controllers:
          main:
            pod:
              securityContext:
                fsGroup: 568
                fsGroupChangePolicy: "OnRootMismatch"
            containers:
              main:
                nameOverride: qbittorrent
                image:
                  repository: ghcr.io/onedr0p/qbittorrent
                  tag: 5.0.4
                env:
                  UMASK: "022"
                  QBITTORRENT__PORT: &port 8080
                securityContext:
                  runAsUser: 568
                  runAsGroup: 568

        service:
          main:
            controller: main
            ports:
              proxy:
                port: 8888
              proxy-udp:
                port: 8888
                protocol: UDP
              http:
                port: *port

        ingress:
          main:
            enabled: true
            className: "kong"
            annotations:
              cert-manager.io/cluster-issuer: letsencrypt-prod
              konghq.com/protocols: https
              konghq.com/https-redirect-status-code: "301"
            hosts:
              - host: &host torrent.suslian.engineer
                paths:
                  - path: /
                    service:
                      identifier: main
                      port: http
            tls:
              - hosts:
                  - *host
                secretName: qbittorrent-tls

        persistence:
          config:
            suffix: config
            enabled: true
            type: persistentVolumeClaim
            accessMode: ReadWriteOnce
            size: 5Gi
          media:
            type: nfs
            server: 192.168.1.252
            path: /mnt/MainHDD/Media/downloads
            advancedMounts:
              main:
                main:
                  - path: /downloads
    repoURL: https://bjw-s-labs.github.io/helm-charts
    targetRevision: 4.0.1
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - PruneLast=true
    - CreateNamespace=true
