immich:
  persistence:
    # Main data store for all photos shared between different components.
    library:
      # Automatically creating the library volume is not supported by this chart
      # You have to specify an existing PVC to use
      existingClaim: photos-nfs

env:
  DB_HOSTNAME: immich-rw

image:
  tag: v1.129.0
# Dependencies

redis:
  enabled: true

postgresql:
  enabled: false

# Immich components

server:
  ingress:
    main:
      enabled: true
      className: "kong"
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        kubernetes.io/ingress.class: kong
        konghq.com/protocols: https
        konghq.com/https-redirect-status-code: "301"
      hosts:
        - host: &host photos.suslian.engineer
          paths:
            - path: "/"
      tls:
        - hosts:
            - *host
          secretName: immich-tls

machine-learning:
  persistence:
    cache:
      enabled: true
      size: 10Gi
      # Optional: Set this to pvc to avoid downloading the ML models every start.
      type: pvc
      accessMode: ReadWriteOnce
