immich:
  persistence:
    # Main data store for all photos shared between different components.
    library:
      # Automatically creating the library volume is not supported by this chart
      # You have to specify an existing PVC to use
      existingClaim: photos-nfs

env:
  DB_URL: postgresql://immich:k.6SA%5Ern%5EJNFc78%2FhUu%3EAKg9@lab-cluster-primary.postgres-operator.svc:5432/immich?sslmode=no-verify

image:
  tag: v1.91.0

# Dependencies

redis:
  enabled: true

postgresql:
  enabled: false

typesense:
  enabled: false
  persistence:
    tsdata:
      # Enabling typesense persistence is recommended to avoid slow reindexing
      enabled: true
      accessMode: ReadWriteOnce
      size: 1Gi

# Immich components

server:
  ingress:
    main:
      enabled: true
      className: "kong"
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        kubernetes.io/ingress.class: kong
        konghq.com/protocols: https
        konghq.com/https-redirect-status-code: "301"
      hosts:
        - host: &host photos.suslian.engineer
          paths:
            - path: "/"
      tls:
        - hosts:
            - *host
          secretName: immich-tls

machine-learning:
  persistence:
    cache:
      enabled: true
      size: 10Gi
      # Optional: Set this to pvc to avoid downloading the ML models every start.
      type: pvc
      accessMode: ReadWriteOnce
