immich:
  persistence:
    # Main data store for all photos shared between different components.
    library:
      # Automatically creating the library volume is not supported by this chart
      # You have to specify an existing PVC to use
      existingClaim: photos-nfs

env:
  DB_USERNAME: postgres
  DB_PASSWORD: postgres

image:
  tag: v1.90.2

# Dependencies

redis:
  enabled: true

postgresql:
  enabled: true
  auth:
    postgresPassword: postgres
  primary:
    extendedConfiguration: |-
      huge_pages = off
    extraVolumeMounts:
      - name: pg-sample-config
        mountPath: /opt/bitnami/postgresql/share/postgresql.conf.sample
        subPath: postgresql.conf.sample
    extraVolumes:
      - configMap:
          name: pg-sample-config
        name:  pg-sample-config
  extraDeploy:
    - apiVersion: v1
      kind: ConfigMap
      metadata:
        name: pg-sample-config
      data:
        postgresql.conf.sample: |-
          huge_pages = off

typesense:
  enabled: false
  persistence:
    tsdata:
      # Enabling typesense persistence is recommended to avoid slow reindexing
      enabled: true
      accessMode: ReadWriteOnce
      size: 1Gi

# Immich components

server:
  ingress:
    main:
      enabled: true
      className: "kong"
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        kubernetes.io/ingress.class: kong
        konghq.com/protocols: https
        konghq.com/https-redirect-status-code: "301"
      hosts:
        - host: &host photos.suslian.engineer
          paths:
            - path: "/"
      tls:
        - hosts:
            - *host
          secretName: immich-tls

machine-learning:
  persistence:
    cache:
      enabled: true
      size: 10Gi
      # Optional: Set this to pvc to avoid downloading the ML models every start.
      type: pvc
      accessMode: ReadWriteOnce
