---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: buildkite-agent
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: in-cluster
    namespace: buildkite
  project: default
  sources:
    - chart: agent-stack-k8s
      helm:
        valueFiles:
          - $values/clusters/k8s-01/apps/buildkite/values.yaml
      repoURL: ghcr.io/buildkite/helm
      targetRevision: 0.49.0
    - path: clusters/k8s-01/apps/buildkite/configs
      repoURL: 'https://github.com/synthe102/homelab.git'
      targetRevision: HEAD
    - repoURL: 'https://github.com/synthe102/homelab.git'
      targetRevision: HEAD
      ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
