apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rook-ceph
  namespace: argocd
spec:
  project: default
  source:
    chart: rook-ceph
    repoURL: https://charts.rook.io/release
    targetRevision: v1.16.5
    helm:
      valuesObject:
        monitoring:
          enabled: true
  destination:
    name: in-cluster
    namespace: rook-ceph
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
