apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rook-ceph
  namespace: argocd
spec:
  project: default
  sources:
  - chart: rook-ceph
    repoURL: https://charts.rook.io/release
    targetRevision: v1.17.0
    helm:
      valuesObject:
        image:
          tag: v1.17.0
        monitoring:
          enabled: true
  - path: clusters/k8s-01/apps/rook/o11y
    repoURL: 'https://github.com/synthe102/homelab.git'
    targetRevision: HEAD
  destination:
    name: in-cluster
    namespace: rook-ceph
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
