apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rook-ceph
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
  - chart: rook-ceph
    repoURL: https://charts.rook.io/release
    targetRevision: v1.17.2
    helm:
      valuesObject:
        monitoring:
          enabled: true
  destination:
    name: in-cluster
    namespace: rook-ceph
  syncPolicy:
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: privileged
    syncOptions:
    - CreateNamespace=true
