---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: gha-runners
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - list:
        elements:
          - org: synthe102
            repo: openpbs-oci
          - org: synthe102
            repo: homelab
          - org: synthe102
            repo: volcan-bot
  template:
    metadata:
      name: 'gha-runner-{{.org}}-{{.repo}}'
    spec:
      project: default
      sources:
        - chart: gha-runner-scale-set
          repoURL: ghcr.io/actions/actions-runner-controller-charts
          targetRevision: 0.14.2
          helm:
            valueFiles:
              - $values/clusters/k8s-01/apps/github-actions/gha-runner-scale-set/values.yaml
            parameters:
              - name: githubConfigUrl
                value: 'https://github.com/{{.org}}/{{.repo}}'
              - name: githubConfigSecret
                value: '{{dig "githubConfigSecret" "runner-auth" .}}'
        - repoURL: 'https://github.com/synthe102/homelab.git'
          targetRevision: HEAD
          ref: values
      destination:
        name: in-cluster
        namespace: arc-system
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
