---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: gha-runners
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - list:
        elements:
          - org: synthe102
            repo: openpbs-oci
          - org: synthe102
            repo: homelab
          - org: synthe102
            repo: volcan-bot
  template:
    metadata:
      name: 'gha-runner-{{.org}}-{{.repo}}'
    spec:
      project: default
      sources:
        - chart: gha-runner-scale-set
          repoURL: ghcr.io/actions/actions-runner-controller-charts
          targetRevision: 0.13.0
          helm:
            valuesObject:
              githubConfigUrl: 'https://github.com/{{.org}}/{{.repo}}'
              githubConfigSecret: '{{dig "githubConfigSecret" "runner-auth" .}}'
              controllerServiceAccount:
                name: gha-runner-scale-set-controller-gha-rs-controller
                namespace: arc-system
              containerMode:
                type: dind
              template:
                spec:
                  containers:
                    - name: runner
                      image: ghcr.io/actions/actions-runner:2.329.0
                      command: ["/home/runner/run.sh"]
                      volumeMounts:
                        - name: certs
                          readOnly: true
                          mountPath: /certs
                  volumes:
                    - name: certs
                      secret:
                        secretName: buildkit-client-certs
      destination:
        name: in-cluster
        namespace: arc-system
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
