apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gha-runner-scale-set-cpu
  namespace: argocd
spec:
  project: default
  sources:
  - chart: gha-runner-scale-set
    repoURL: ghcr.io/actions/actions-runner-controller-charts
    targetRevision: 0.11.0
    helm:
      releaseName: self-hosted-cpu
      valuesObject:
        githubConfigUrl: "https://github.com/synthe102/openpbs-oci"
        githubConfigSecret: runner-auth
        controllerServiceAccount:
          name: gha-runner-scale-set-controller-gha-rs-controller
          namespace: arc-system
        containerMode:
          type: dind
  destination:
    name: in-cluster
    namespace: arc-system
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
