apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: irq-balance
  namespace: argocd
spec:
  project: default
  source:
    chart: app-template
    repoURL: https://bjw-s.github.io/helm-charts
    targetRevision: 3.7.2
    helm:
      valuesObject:
        controllers:
          irqbalance:
            type: daemonset
            containers:
              app:
                image:
                  repository: ghcr.io/buroa/irqbalance
                  tag: 1.9.4
                env:
                  IRQBALANCE_BANNED_CPULIST: 12-19 # 12-19 are E-cores
                resources:
                  requests:
                    cpu: 10m
                  limits:
                    memory: 32Mi
                securityContext:
                  privileged: true
        defaultPodOptions:
          hostIPC: true
          hostPID: true
        persistence:
          run:
            type: emptyDir
            globalMounts:
              - path: /run/irqbalance
  destination:
    name: in-cluster
    namespace: kube-system
