controllers:
  main:
    containers:
      main:
        nameOverride: kavita-mail
        image:
          repository: jvmilazz0/kavitaemail
          tag: 0.1.25

service:
  main:
    ports:
      http:
        port: 5003

persistence:
  config:
    enabled: true
    type: persistentVolumeClaim
    accessMode: ReadWriteOnce
    size: 5Gi
    advancedMounts:
      main:
        main:
          - path: /app/config
