---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
  - name: mosquitto-configmap
    files:
      - mosquitto.conf
generatorOptions:
  disableNameSuffixHash: true
