---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: agent-sandbox
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://github.com/kubernetes-sigs/agent-sandbox.git
      # renovate: datasource=github-releases depName=kubernetes-sigs/agent-sandbox
      targetRevision: v0.4.6
      path: helm
      helm:
        releaseName: agent-sandbox
        valuesObject:
          image:
            # renovate: datasource=github-releases depName=kubernetes-sigs/agent-sandbox
            tag: v0.4.6
          namespace:
            create: true
            name: agent-sandbox
    - repoURL: https://github.com/synthe102/homelab.git
      targetRevision: HEAD
      path: clusters/k8s-01/apps/ai/agent-sandbox/configs
  destination:
    name: in-cluster
    namespace: agent-sandbox
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
