apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metrics-server
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: in-cluster
    namespace: kube-system
  project: default
  sources:
  - chart: metrics-server
    helm:
      valueFiles:
      - $values/k8s/sources/kube-system/metrics-server/values.yaml
    repoURL: https://kubernetes-sigs.github.io/metrics-server
    targetRevision: 3.12.*
  - ref: values
    repoURL: https://github.com/synthe102/homelab.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - PruneLast=true
    - CreateNamespace=true
    - ServerSideApply=true
