apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metrics-server
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: kube-system
  project: default
  sources:
  - chart: metrics-server
    helm:
      valueFiles:
      - $values/k8s/sources/metrics-server/values.yaml
    repoURL: https://kubernetes-sigs.github.io/metrics-server
    targetRevision: 3.11.*
  - ref: values
    repoURL: https://github.com/synthe102/homelab.git
    targetRevision: main
  - path: k8s/sources/metrics-server/manifests
    repoURL: https://github.com/synthe102/homelab.git
    targetRevision: main
  syncPolicy:
    syncOptions:
    - PruneLast=true
    - CreateNamespace=true
    - ServerSideApply=true
