controllers:
  main:
    pod:
      securityContext:
        fsGroup: 568
        fsGroupChangePolicy: "OnRootMismatch"

    containers:
      main:
        nameOverride: bazarr
        image:
          repository: ghcr.io/onedr0p/bazarr
          tag: 1.4.2
        env:
          UMASK: "022"
          TZ: "Europe/Paris"
        securityContext:
          runAsUser: 568
          runAsGroup: 568

service:
  main:
    ports:
      http:
        port: 6767

ingress:
  main:
    enabled: true
    className: "kong"
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      konghq.com/protocols: https
      konghq.com/https-redirect-status-code: "301"
    hosts:
      - host: &host bazarr.suslian.engineer
        paths:
          - path: /
            service:
              name: main
              port: http
    tls:
      - hosts:
          - *host
        secretName: bazarr-tls

persistence:
  config:
    enabled: true
    type: persistentVolumeClaim
    existingClaim: bazarr-config
  media:
    type: nfs
    server: 192.168.1.252
    path: /mnt/MainHDD/Media
