---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jellyseerr
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: in-cluster
    namespace: media
  project: default
  sources:
    - chart: app-template
      helm:
        valuesObject:
          controllers:
            main:
              pod:
                securityContext:
                  fsGroup: 568
                  fsGroupChangePolicy: "OnRootMismatch"
              containers:
                main:
                  nameOverride: jellyseerr
                  image:
                    repository: fallenbagel/jellyseerr
                    tag: 2.6.0
                  env:
                    UMASK: "022"
                    TZ: "Europe/Paris"
                  securityContext:
                    runAsUser: 568
                    runAsGroup: 568
          service:
            main:
              controller: main
              ports:
                http:
                  port: 5055
          ingress:
            main:
              enabled: true
              className: "kong"
              annotations:
                cert-manager.io/cluster-issuer: letsencrypt-prod
                konghq.com/protocols: https
                konghq.com/https-redirect-status-code: "301"
              hosts:
                - host: &host requests.suslian.engineer
                  paths:
                    - path: /
                      service:
                        identifier: main
                        port: http
              tls:
                - hosts:
                    - *host
                  secretName: jellyseerr-tls
          persistence:
            config:
              suffix: config
              enabled: true
              type: persistentVolumeClaim
              accessMode: ReadWriteOnce
              size: 5Gi
              advancedMounts:
                main:
                  main:
                    - path: /app/config
      repoURL: https://bjw-s-labs.github.io/helm-charts
      targetRevision: 4.1.0
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
