---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: multus-vpn-routed
spec:
  config: |-
    {
      "cniVersion": "0.3.1",
      "name": "multus-vpn-routed",
      "plugins": [
        {
          "type": "macvlan",
          "master": "enp2cc14f4.100",
          "mode": "bridge",
          "ipam": {
            "type": "static",
            "routes": [
              {"dst": "0.0.0.0/0", "gw": "10.0.100.1"}
            ]
          }
        },
        {
          "type": "sbr"
        }
      ]
    }
