---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: immich
spec:
  instances: 2
  enableSuperuserAccess: true
  bootstrap:
    initdb:
      database: immich
      owner: immich
      secret:
        name: immich-db-user
      dataChecksums: true
      encoding: 'UTF8'
  storage:
    size: 8Gi
  resources:
    requests:
      memory: "512Mi"
    limits:
      hugepages-2Mi: "512Mi"
