apiVersion: v1
kind: PersistentVolume
metadata:
  name: photos-nfs
  labels:
    type: nfs
    content: photos
spec:
  capacity:
    storage: 8Ti
  volumeMode: Filesystem
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - nfsvers=4.2
  nfs:
    path: /mnt/MainHDD/Photos
    server: 192.168.1.252
