apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: photos-nfs
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  storageClassName: nfs
  resources:
    requests:
      storage: 8Ti
  selector:
    matchLabels:
      type: nfs
      content: photos
