---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: slurm
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  ignoreDifferences:
    - kind: Secret
      jsonPointers:
        - /data/jwt_hs256.key
        - /data/slurm.key
  sources:
    - chart: slurm
      repoURL: ghcr.io/slinkyproject/charts
      targetRevision: 1.0.0
      helm:
        valuesObject:
          controller:
            metrics:
              enabled: true
              serviceMonitor:
                enabled: true
          loginsets:
            slinky:
              enabled: true
              rootSshAuthorizedKeys: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPpImAuOJLlSWirZ4ZZVny3rycrioOJedfEx8I2BRRRD leonard@suslian.engineer
  destination:
    name: in-cluster
    namespace: slurm
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: privileged
    syncOptions:
      - CreateNamespace=true
