apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-snapshotter
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
  - path: client/config/crd
    repoURL: 'https://github.com/kubernetes-csi/external-snapshotter.git'
    targetRevision: v8.2.1
  - path: deploy/kubernetes/snapshot-controller
    repoURL: 'https://github.com/kubernetes-csi/external-snapshotter.git'
    targetRevision: v8.2.1
  destination:
    name: in-cluster
    namespace: kube-system
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
