---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: &name harbor
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - path: clusters/k8s-01/apps/registry/harbor/configs
      repoURL: 'https://github.com/synthe102/homelab.git'
      targetRevision: HEAD
    - chart: harbor
      repoURL: https://helm.goharbor.io
      targetRevision: 1.19.2
      helm:
        valuesObject:
          expose:
            type: route
            tls:
              enabled: false
            route:
              parentRefs:
                - group: gateway.networking.k8s.io
                  kind: Gateway
                  name: internal
                  namespace: kube-system
                  sectionName: https-k8s-01
              hosts:
                - harbor.k8s-01.suslian.engineer
          externalURL: https://harbor.k8s-01.suslian.engineer
          existingSecretAdminPassword: harbor-secrets
          existingSecretAdminPasswordKey: HARBOR_ADMIN_PASSWORD
          existingSecretSecretKey: harbor-secrets
          persistence:
            enabled: true
            resourcePolicy: keep
            persistentVolumeClaim:
              redis:
                storageClass: ceph-block-xfs
                size: 2Gi
              trivy:
                storageClass: ceph-block-xfs
                size: 10Gi
            imageChartStorage:
              type: s3
              disableredirect: true
              s3:
                existingSecret: harbor-registry-s3
                region: us-east-1
                bucket: harbor-registry
                regionendpoint: http://rook-ceph-rgw-ceph-objectstore.rook-ceph.svc
                secure: false
                skipverify: false
                v4auth: true
          metrics:
            enabled: true
            serviceMonitor:
              enabled: true
          core:
            replicas: 2
            existingSecret: harbor-secrets
            secretName: harbor-token
            existingXsrfSecret: harbor-secrets
            existingXsrfSecretKey: CSRF_KEY
            podDisruptionBudget:
              enabled: true
              minAvailable: 1
            nodeSelector:
              kubernetes.io/arch: amd64
            topologySpreadConstraints:
              - maxSkew: 1
                topologyKey: kubernetes.io/hostname
                whenUnsatisfiable: ScheduleAnyway
            resources:
              requests:
                cpu: 100m
                memory: 256Mi
          portal:
            replicas: 2
            podDisruptionBudget:
              enabled: true
              minAvailable: 1
            nodeSelector:
              kubernetes.io/arch: amd64
            topologySpreadConstraints:
              - maxSkew: 1
                topologyKey: kubernetes.io/hostname
                whenUnsatisfiable: ScheduleAnyway
            resources:
              requests:
                cpu: 25m
                memory: 64Mi
          jobservice:
            replicas: 2
            existingSecret: harbor-secrets
            existingSecretKey: JOBSERVICE_SECRET
            jobLoggers:
              - database
            podDisruptionBudget:
              enabled: true
              minAvailable: 1
            nodeSelector:
              kubernetes.io/arch: amd64
            topologySpreadConstraints:
              - maxSkew: 1
                topologyKey: kubernetes.io/hostname
                whenUnsatisfiable: ScheduleAnyway
            resources:
              requests:
                cpu: 50m
                memory: 128Mi
          registry:
            replicas: 2
            existingSecret: harbor-secrets
            existingSecretKey: REGISTRY_HTTP_SECRET
            credentials:
              username: harbor_registry_user
              existingSecret: harbor-secrets
            podDisruptionBudget:
              enabled: true
              minAvailable: 1
            nodeSelector:
              kubernetes.io/arch: amd64
            topologySpreadConstraints:
              - maxSkew: 1
                topologyKey: kubernetes.io/hostname
                whenUnsatisfiable: ScheduleAnyway
            registry:
              resources:
                requests:
                  cpu: 100m
                  memory: 256Mi
            controller:
              resources:
                requests:
                  cpu: 50m
                  memory: 128Mi
          trivy:
            nodeSelector:
              kubernetes.io/arch: amd64
          database:
            type: external
            external:
              host: harbor-db-rw
              port: "5432"
              username: harbor
              coreDatabase: registry
              existingSecret: harbor-db-app
              sslmode: require
            maxIdleConns: 10
            maxOpenConns: 30
          redis:
            type: internal
            internal:
              nodeSelector:
                kubernetes.io/arch: amd64
              resources:
                requests:
                  cpu: 50m
                  memory: 128Mi
          exporter:
            nodeSelector:
              kubernetes.io/arch: amd64
            resources:
              requests:
                cpu: 25m
                memory: 64Mi
  destination:
    name: in-cluster
    namespace: *name
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
