metallb:
  configInline:
    address-pools:
    - name: default
      protocol: layer2
      addresses:
      - 192.168.1.240-192.168.1.249
    - name: pihole
      protocol: layer2
      addresses:
      - 192.168.1.253/32