apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: in-cluster
    namespace: external-secrets
  project: default
  sources:
  - chart: external-secrets
    helm:
      valueFiles:
      - $values/k8s/sources/external-secrets/values.yaml
    repoURL: https://charts.external-secrets.io
    targetRevision: 0.9.*
  - ref: values
    repoURL: https://github.com/synthe102/homelab.git
    targetRevision: main
  - path: k8s/sources/external-secrets/manifests
    repoURL: https://github.com/synthe102/homelab.git
    targetRevision: main
  syncPolicy:
    syncOptions:
    - PruneLast=true
    - CreateNamespace=true
    - ServerSideApply=true
