---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: node-problem-detector
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: node-problem-detector
    repoURL: ghcr.io/deliveryhero/helm-charts
    targetRevision: 2.4.0
    helm:
      valuesObject:
        metrics:
          enabled: true
          serviceMonitor:
            enabled: true
          prometheusRule:
            enabled: true
  destination:
    name: in-cluster
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
