---
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: harbor-passwords
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  length: 32
  digits: 8
  symbols: 0
  allowRepeat: true
  secretKeys:
    - HARBOR_ADMIN_PASSWORD
    - REGISTRY_PASSWD
---
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: harbor-secret-keys
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  length: 16
  digits: 4
  symbols: 0
  allowRepeat: true
  secretKeys:
    - secretKey
    - secret
    - JOBSERVICE_SECRET
    - REGISTRY_HTTP_SECRET
---
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: harbor-xsrf-key
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  length: 32
  digits: 8
  symbols: 0
  allowRepeat: true
  secretKeys:
    - CSRF_KEY
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: harbor-secrets
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshPolicy: CreatedOnce
  target:
    name: harbor-secrets
    creationPolicy: Orphan
    deletionPolicy: Retain
    immutable: true
    template:
      engineVersion: v2
      mergePolicy: Merge
      type: Opaque
      data:
        REGISTRY_HTPASSWD: '{{ htpasswd "harbor_registry_user" .REGISTRY_PASSWD "bcrypt" }}'
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: harbor-passwords
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: harbor-secret-keys
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: harbor-xsrf-key
