---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: whisper
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: in-cluster
    namespace: home-automation
  project: default
  sources:
    - repoURL: https://bjw-s-labs.github.io/helm-charts
      targetRevision: 4.4.0
      chart: app-template
      helm:
        valuesObject:
          controllers:
            main:
              containers:
                main:
                  image:
                    repository: rhasspy/wyoming-whisper-cpp
                    tag: 1.1.0
                  args:
                    - --language
                    - en
                    - --model
                    - small
                    - --data-dir
                    - /data
          service:
            main:
              ports:
                http:
                  port: 10300
          persistence:
            data:
              enabled: true
              type: persistentVolumeClaim
              accessMode: ReadWriteOnce
              size: 5Gi
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
