external-dns:
  provider: pihole
  env:
    - name: EXTERNAL_DNS_PIHOLE_PASSWORD
      valueFrom:
        secretKeyRef:
          name: pihole-password
          key: EXTERNAL_DNS_PIHOLE_PASSWORD
  extraArgs:
    - --registry=noop
    - --pihole-server=http://192.168.1.253
