external-dns:
  image:
    # adds pihole support
    tag: v0.13.2
  provider: pihole
  env:
    - name: EXTERNAL_DNS_PIHOLE_PASSWORD
      valueFrom:
        secretKeyRef:
          name: pihole-password
          key: EXTERNAL_DNS_PIHOLE_PASSWORD
  registry: noop
  extraArgs:
    - --pihole-server=http://192.168.1.253
