---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: auth
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: bitwarden-homelab
    kind: ClusterSecretStore
  target:
    template:
      metadata:
        labels:
          app.kubernetes.io/part-of: argocd
  dataFrom:
    - extract:
        key: "K8S_01_KUBE_ARGOCD_AUTH"
