apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: velero
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
  - chart: velero
    repoURL: https://vmware-tanzu.github.io/helm-charts
    targetRevision: 9.0.4
    helm:
      valuesObject:
        deployNodeAgent: true
        configuration:
          features: EnableCSI
          backupStorageLocation:
          - name: cloudflare
            provider: aws
            default: true
            bucket: k8s-01-backups
            credential:
              name: cloudflare-r2
              key: credentials
            config:
              region: auto
              s3Url: https://6815e9f87446426c602fab643b303d4f.eu.r2.cloudflarestorage.com
          volumeSnapshotLocation:
          - name: cloudflare
            provider: aws
            default: true
            credential:
              name: cloudflare-r2
              key: credentials
            config:
              region: auto
        initContainers:
        - name: velero-plugin-for-aws
          image: velero/velero-plugin-for-aws:v1.12.0
          volumeMounts:
          - mountPath: /target
            name: plugins
  - path: clusters/k8s-01/apps/velero/configs
    repoURL: 'https://github.com/synthe102/homelab.git'
    targetRevision: HEAD
  destination:
    name: in-cluster
    namespace: velero-system
  syncPolicy:
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: privileged
    syncOptions:
    - CreateNamespace=true
