---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: velero
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: 'https://github.com/synthe102/homelab.git'
      targetRevision: HEAD
      ref: values
    - chart: velero
      repoURL: https://vmware-tanzu.github.io/helm-charts
      targetRevision: 11.3.1
      helm:
        valueFiles:
          - $values/clusters/k8s-01/apps/velero/values.yaml
    - path: clusters/k8s-01/apps/velero/configs
      repoURL: 'https://github.com/synthe102/homelab.git'
      targetRevision: HEAD
  destination:
    name: in-cluster
    namespace: velero-system
  syncPolicy:
    automated:
      selfHeal: true
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: privileged
    syncOptions:
      - CreateNamespace=true
