---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: satisfactory-volcan
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: in-cluster
    namespace: game-servers
  project: default
  sources:
    - repoURL: 'https://github.com/synthe102/homelab.git'
      targetRevision: HEAD
      ref: values
    - chart: app-template
      helm:
        valueFiles:
          - $values/clusters/k8s-01/apps/game-servers/satisfactory/values.yaml
      repoURL: https://bjw-s-labs.github.io/helm-charts
      targetRevision: 4.5.0
    - path: clusters/k8s-01/apps/game-servers/satisfactory/configs
      repoURL: 'https://github.com/synthe102/homelab.git'
      targetRevision: HEAD
  syncPolicy:
    # automated:
    #   prune: true
    #   selfHeal: true
    syncOptions:
      - CreateNamespace=true
