---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: immich
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - chart: immich
      helm:
        valuesObject:
          immich:
            persistence:
              library:
                existingClaim: photos-nfs
          env:
            DB_VECTOR_EXTENSION: vectorchord
            DB_URL:
              valueFrom:
                secretKeyRef:
                  name: immich-app
                  key: uri
          image:
            # renovate: datasource=docker depName=ghcr.io/immich-app/immich-server
            tag: &tag v1.142.0
          redis:
            enabled: true
            master:
              resources:
                requests:
                  cpu: 0.2
                  memory: 256Mi
                limits:
                  memory: 256Mi
          server:
            controller:
              strategy: Recreate
            resources:
              requests:
                gpu.intel.com/i915: "1"
                memory: 4Gi
              limits:
                gpu.intel.com/i915: "1"
                memory: 4Gi
          machine-learning:
            controller:
              strategy: Recreate
            image:
              # renovate: datasource=docker depName=ghcr.io/immich-app/immich-machine-learning
              tag: v1.142.0-openvino
            resources:
              requests:
                gpu.intel.com/i915: "1"
                memory: 4Gi
              limits:
                gpu.intel.com/i915: "1"
                memory: 4Gi
            persistence:
              cache:
                enabled: true
                size: 10Gi
                # Optional: Set this to pvc to avoid downloading the ML models every start.
                type: pvc
                accessMode: ReadWriteOnce
      repoURL: https://immich-app.github.io/immich-charts
      targetRevision: 0.9.3
    - path: clusters/k8s-01/apps/media/immich/configs
      repoURL: 'https://github.com/synthe102/homelab.git'
      targetRevision: HEAD
  destination:
    name: in-cluster
    namespace: media
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
