apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: immich
  namespace: argocd
spec:
  project: default
  sources:
  - path: clusters/k8s-01/apps/media/immich/configs
    repoURL: 'https://github.com/synthe102/homelab.git'
    targetRevision: HEAD
  destination:
    name: in-cluster
    namespace: media
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
