---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: 'https://github.com/synthe102/homelab.git'
      targetRevision: HEAD
      ref: values
    - chart: external-secrets
      repoURL: https://charts.external-secrets.io
      targetRevision: 1.2.0
      helm:
        valueFiles:
          - $values/clusters/k8s-01/apps/external-secrets/values.yaml
    - path: clusters/k8s-01/apps/external-secrets/configs
      repoURL: 'https://github.com/synthe102/homelab.git'
      targetRevision: HEAD
  destination:
    name: in-cluster
    namespace: external-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - DisableClientSideApplyMigration=true
