apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
  - chart: external-secrets
    repoURL: https://charts.external-secrets.io
    targetRevision: 0.17.0
    helm:
      valuesObject:
        grafanaDashboard:
          enabled: true
        serviceMonitor:
          enabled: true
        bitwarden-sdk-server:
          enabled: true
  - path: clusters/k8s-01/apps/external-secrets/configs
    repoURL: 'https://github.com/synthe102/homelab.git'
    targetRevision: HEAD
  destination:
    name: in-cluster
    namespace: external-secrets
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
