---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: authentik-db
spec:
  instances: 2
  managed:
    roles:
      - name: &name authentik
        superuser: true
        login: true
  bootstrap:
    initdb:
      database: *name
      owner: *name
  storage:
    size: 8Gi
  resources:
    requests:
      memory: "512Mi"
