
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: authentik-secret-key
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-homelab
    kind: ClusterSecretStore
  data:
  - secretKey: secret-key
    remoteRef:
      key: "K8S_01_KUBE_AUTHENTIK_SECRET_KEY"
