cloudflared:
  replicaCount: 2
  image:
    tag: 2022.1.2
  credentials:
    existingSecret: cloudflared-credentials
  config:
    tunnel: homelab
    ingress:
      - hostname: '*.suslian.engineer'
        service: https://ingress-nginx-controller.ingress-nginx
        originRequest:
          noTLSVerify: true
      - service: http_status:404
