controllers:
  main:
    pod:
      securityContext:
        fsGroup: 568
        fsGroupChangePolicy: "OnRootMismatch"

    containers:
      main:
        resources:
          requests:
            gpu.intel.com/i915: 1
          limits:
            gpu.intel.com/i915: 1
        nameOverride: sonarr
        image:
          repository: ghcr.io/onedr0p/sonarr
          tag: 3.0.10
        env:
          UMASK: "022"
          TZ: "Europe/Paris"
        securityContext:
          runAsUser: 568
          runAsGroup: 568

service:
  main:
    ports:
      http:
        port: 8096

ingress:
  main:
    enabled: true
    className: "cilium"
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
    hosts:
      - host: &host sonarr.suslian.engineer
        paths:
          - path: /
            service:
              name: main
              port: http
    tls:
      - hosts:
          - *host
        secretName: sonarr-tls

persistence:
  config:
    enabled: true
    type: persistentVolumeClaim
    existingClaim: sonarr-config
  media:
    type: nfs
    server: 192.168.1.252
    path: /mnt/MainHDD/Media
