controllers:
  main:
    containers:
      main:
        nameOverride: calibre
        image:
          repository: ghcr.io/linuxserver/calibre
          tag: 7.12.0
        env:
          UMASK: "022"
          TZ: "Europe/Paris"
          PUID: 1000
          PGID: 1000

service:
  main:
    ports:
      http:
        port: 8080
      content:
        port: 8081

ingress:
  main:
    enabled: true
    className: "kong"
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      konghq.com/protocols: https
      konghq.com/https-redirect-status-code: "301"
    hosts:
      - host: &host calibre.suslian.engineer
        paths:
          - path: /
            service:
              name: main
              port: http
    tls:
      - hosts:
          - *host
        secretName: calibre-tls

persistence:
  config:
    enabled: true
    type: persistentVolumeClaim
    accessMode: ReadWriteOnce
    size: 5Gi
  media:
    type: nfs
    server: 192.168.1.252
    path: /mnt/MainHDD/Media
