---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sonarr
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: in-cluster
    namespace: downloads
  project: default
  sources:
    - chart: app-template
      helm:
        valuesObject:
          controllers:
            main:
              pod:
                securityContext:
                  fsGroup: 568
                  fsGroupChangePolicy: "OnRootMismatch"
              containers:
                main:
                  nameOverride: sonarr
                  image:
                    repository: ghcr.io/home-operations/sonarr
                    tag: 4.0.15
                  env:
                    SONARR__PORT: &port 8989
                    UMASK: "022"
                    TZ: "Europe/Paris"
                  securityContext:
                    runAsUser: 568
                    runAsGroup: 568
          service:
            main:
              controller: main
              ports:
                http:
                  port: *port 
          persistence:
            config:
              suffix: config
              enabled: true
              type: persistentVolumeClaim
              accessMode: ReadWriteOnce
              size: 5Gi
            media:
              type: nfs
              server: 192.168.1.252
              path: /mnt/MainHDD/Media
          route:
            app:
              hostnames:
                - sonarr.suslian.engineer
              parentRefs:
                - name: internal
                  namespace: kube-system
                  sectionName: https
      repoURL: https://bjw-s-labs.github.io/helm-charts
      targetRevision: 4.1.2
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
