---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - kube-prometheus-stack
  - grafana-mcp
  - loki
  - mimir
  - mimir-kafka
  - unpoller
  - smartctl-exporter
  - k8s-monitoring
  - pyroscope
  - tempo
