apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: unifi-tls
  namespace: unifi
spec:
  dnsNames:
  - unifi.suslian.engineer
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-prod
  secretName: unifi-tls
