---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: &app unpoller
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - chart: app-template
      repoURL: https://bjw-s-labs.github.io/helm-charts
      targetRevision: 4.4.0
      helm:
        valuesObject:
          controllers:
            unpoller:
              containers:
                app:
                  image:
                    repository: ghcr.io/unpoller/unpoller
                    tag: v2.15.4
                  env:
                    TZ: Europe/Paris
                    UP_UNIFI_DEFAULT_ROLE: Monitoring
                    UP_UNIFI_DEFAULT_VERIFY_SSL: false
                    UP_INFLUXDB_DISABLE: true
                    UP_LOKI_DISABLE: "false"
                    UP_LOKI_URL: "http://loki:3100"
                    UP_UNIFI_DEFAULT_SAVE_ALARMS: "true"
                    UP_UNIFI_DEFAULT_SAVE_ANOMALIES: "true"
                    UP_UNIFI_DEFAULT_SAVE_DPI: "true"
                    UP_UNIFI_DEFAULT_SAVE_EVENTS: "true"
                    UP_UNIFI_DEFAULT_SAVE_IDS: "true"
                  envFrom:
                    - secretRef:
                        name: unpoller
                  probes:
                    liveness:
                      enabled: true
                    readiness:
                      enabled: true
                  resources:
                    requests:
                      cpu: 10m
                    limits:
                      memory: 64Mi
                  securityContext:
                    allowPrivilegeEscalation: false
                    readOnlyRootFilesystem: true
                    capabilities: {drop: ["ALL"]}
          defaultPodOptions:
            securityContext:
              runAsNonRoot: true
              runAsUser: 568
              runAsGroup: 568
          service:
            app:
              controller: *app
              ports:
                http:
                  port: 9130
          serviceMonitor:
            app:
              serviceName: *app
              endpoints:
                - port: http
                  interval: 30s
                  scrapeTimeout: 10s
    - path: clusters/k8s-01/apps/monitoring/unpoller/configs
      repoURL: 'https://github.com/synthe102/homelab.git'
      targetRevision: HEAD
  destination:
    name: in-cluster
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
