---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cilium
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  ignoreDifferences:
    - kind: Secret
      jsonPointers:
        - /data/ca.crt
        - /data/ca.key
        - /data/tls.crt
        - /data/tls.key
  sources:
    - repoURL: 'https://github.com/synthe102/homelab.git'
      targetRevision: HEAD
      ref: values
    - chart: cilium
      repoURL: https://helm.cilium.io/
      targetRevision: 1.18.5
      helm:
        apiVersions:
          - monitoring.coreos.com/v1
        valueFiles:
          - $values/clusters/k8s-01/apps/kube-system/cilium/values.yaml
    - path: clusters/k8s-01/apps/kube-system/cilium/configs
      repoURL: 'https://github.com/synthe102/homelab.git'
      targetRevision: HEAD
  destination:
    name: in-cluster
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
