---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cilium
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  ignoreDifferences:
    - kind: Secret
      jsonPointers:
        - /data/ca.crt
        - /data/ca.key
        - /data/tls.crt
        - /data/tls.key
  sources:
    - path: clusters/k8s-01/apps/kube-system/cilium/configs
      repoURL: 'https://github.com/synthe102/homelab.git'
      targetRevision: HEAD
    - chart: cilium
      repoURL: https://helm.cilium.io/
      targetRevision: 1.18.1
      helm:
        apiVersions:
          - monitoring.coreos.com/v1
        valuesObject:
          hubble:
            metrics:
              enabled: [dns, drop, tcp, flow, port-distribution, icmp, 'httpV2:exemplars=true;labelsContext=source_ip,source_namespace,source_workload,destination_ip,destination_namespace,destination_workload,traffic_direction']
              enableOpenMetrics: true
              serviceMonitor:
                enabled: true
              dashboards:
                enabled: true
            relay:
              enabled: true
              rollOutPods: true
            ui:
              enabled: true
              rollOutPods: true
          dashboards:
            enabled: true
            annotations:
              argocd.argoproj.io/sync-options: ServerSideApply=true
          prometheus:
            enabled: true
            serviceMonitor:
              enabled: true
          gatewayAPI:
            enabled: true
            enableAlpn: true
            gatewayClass:
              create: "true"
          envoy:
            rollOutPods: true
            prometheus:
              serviceMonitor:
                enabled: true
          bpf:
            datapathMode: netkit-l2
            masquerade: true
            preallocateMaps: true
          autoDirectNodeRoutes: true
          ipv4NativeRoutingCIDR: 10.244.0.0/16
          routingMode: native
          bgpControlPlane:
            enabled: true
          ipam:
            mode: kubernetes
          kubeProxyReplacement: true
          securityContext:
            capabilities:
              ciliumAgent: [CHOWN, KILL, NET_ADMIN, NET_RAW, IPC_LOCK, SYS_ADMIN, SYS_RESOURCE, DAC_OVERRIDE, FOWNER, SETGID, SETUID]
              cleanCiliumState: [NET_ADMIN, SYS_ADMIN, SYS_RESOURCE]
          cgroup:
            autoMount:
              enabled: false
            hostRoot: /sys/fs/cgroup
          k8sServiceHost: localhost
          k8sServicePort: 7445
          operator:
            rollOutPods: true
            dashboards:
              enabled: true
            prometheus:
              serviceMonitor:
                enabled: true
          rollOutCiliumPods: true
          cni:
            exclusive: false
  destination:
    name: in-cluster
    namespace: kube-system
  syncPolicy:
    # automated:
    #   prune: true
    #   selfHeal: true
    syncOptions:
      - CreateNamespace=true
