---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vaultwarden
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: in-cluster
    namespace: tooling
  project: default
  sources:
    - chart: app-template
      helm:
        valuesObject:
          controllers:
            main:
              containers:
                main:
                  nameOverride: vaultwarden
                  image:
                    repository: ghcr.io/dani-garcia/vaultwarden
                    tag: 1.34.2
                  env:
                    DATABASE_URL:
                      secretKeyRef:
                        name: vaultwarden
                        key: DATABASE_URL
          service:
            main:
              controller: main
              ports:
                http:
                  port: 80
          persistence:
            key:
              type: secret
              name: vaultwarden
              advancedMounts:
                main:
                  main:
                    - path: /data/rsa_key.pem
                      readOnly: true
                      subPath: rsa_key.pem
          route:
            app:
              hostnames:
                - vaultwarden.suslian.engineer
              parentRefs:
                - name: internal
                  namespace: kube-system
                  sectionName: https
      repoURL: https://bjw-s-labs.github.io/helm-charts
      targetRevision: 4.2.0
    - path: clusters/k8s-01/apps/tooling/vaultwarden/configs
      repoURL: 'https://github.com/synthe102/homelab.git'
      targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
