apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: external-dns-unifi-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-homelab
    kind: ClusterSecretStore
  data:
  - secretKey: api-key
    remoteRef:
      key: "K8S_01_KUBE_EXTERNAL_DNS_UNIFI_API_KEY"
