apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dp-gpu
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: intel-device-plugins-gpu
    repoURL: https://intel.github.io/helm-charts
    targetRevision: 0.32.0
    helm:
      valuesObject:
        name: i915
        nodeFeatureRule: false
        sharedDevNum: 2 # Allow 2 Pod per GPU
  destination:
    name: in-cluster
    namespace: kube-system
