apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: qbittorrent-vpn-config
  namespace: download
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-auth-api
  target:
    name: qbittorrent-vpn-config
  data:
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: DOWNLOAD_VPN_ENDPOINT_IP
        metadataPolicy: None
      secretKey: VPN_ENDPOINT_IP
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: DOWNLOAD_WIREGUARD_ADDRESSES
        metadataPolicy: None
      secretKey: WIREGUARD_ADDRESSES
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: DOWNLOAD_WIREGUARD_PRIVATE_KEY
        metadataPolicy: None
      secretKey: WIREGUARD_PRIVATE_KEY
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: DOWNLOAD_WIREGUARD_PUBLIC_KEY
        metadataPolicy: None
      secretKey: WIREGUARD_PUBLIC_KEY
