apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: qbittorrent-vpn-config
  namespace: download
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-auth-api
  target:
    name: qbittorrent-vpn-config
  data:
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: DOWNLOAD_SERVER_HOSTNAME
        metadataPolicy: None
      secretKey: DOWNLOAD_SERVER_HOSTNAME
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: DOWNLOAD_WIREGUARD_PRIVATE_KEY
        metadataPolicy: None
      secretKey: WIREGUARD_PRIVATE_KEY
