controllers:
  main:
    containers:
      main:
        nameOverride: lazylibrarian
        image:
          repository: linuxserver/lazylibrarian
          tag: 132dc7bd-ls26
        env:
          PUID: 1000
          PGID: 1000
          UMASK: "022"
          TZ: "Europe/Paris"

service:
  main:
    ports:
      http:
        port: 5299

ingress:
  main:
    enabled: true
    className: "kong"
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      konghq.com/protocols: https
      konghq.com/https-redirect-status-code: "301"
    hosts:
      - host: &host books.suslian.engineer
        paths:
          - path: /
            service:
              name: main
              port: http
    tls:
      - hosts:
          - *host
        secretName: lazylibrarian-tls

persistence:
  config:
    enabled: true
    type: persistentVolumeClaim
    accessMode: ReadWriteOnce
    size: 5Gi
  media:
    type: nfs
    server: 192.168.1.252
    path: /mnt/MainHDD/Media
