{{- range $index, $issuer := .Values.issuers }}
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ $issuer.name }}
spec:
  acme:
    server: {{ $issuer.server }}
    email: {{ $.Values.email }}
    privateKeySecretRef:
      name: {{ $issuer.name }}
    solvers:
    - dns01:
        cloudflare:
          email: {{ $issuer.email }}
          apiTokenSecretRef:
            name: cloudflare-api-token
            key: api-token
{{- end}}