apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: in-cluster
  project: default
  source:
    path: clusters/k8s-01/apps
    repoURL: https://github.com/synthe102/homelab.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true
