apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: unifi
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: in-cluster
    namespace: unifi
  project: default
  sources:
  - chart: app-template
    helm:
      valueFiles:
      - $values/k8s/sources/unifi/values.yaml
    repoURL: https://bjw-s.github.io/helm-charts
    targetRevision: 2.6.*
  - ref: values
    repoURL: https://github.com/synthe102/homelab.git
    targetRevision: main
  - path: k8s/sources/unifi/manifests
    repoURL: https://github.com/synthe102/homelab.git
    targetRevision: main
  syncPolicy:
    syncOptions:
    - PruneLast=true
    - CreateNamespace=true
    - ServerSideApply=true
