controllers:
  main:
    pod:
      securityContext:
        fsGroup: 999

    containers:
      main:
        nameOverride: unifi
        image:
          repository: ghcr.io/goofball222/unifi
          tag: 8.0.28
        securityContext:
          runAsUser: 999
          runAsGroup: 999
        env:
          - name: TZ
            value: UTC
        ports:
          - name: stun
            containerPort: 3478
            protocol: UDP
          - name: throughput
            containerPort: 6789
          - name: inform
            containerPort: 8080
          - name: gui
            containerPort: 8443
          - name: http
            containerPort: 8880
          - name: https
            containerPort: 8843
          - name: discovery
            containerPort: 10001
            protocol: UDP


service:
  main:
    annotations:
      konghq.com/protocol: https
    type: LoadBalancer
    ports:
      stun:
        port: 3478
        protocol: UDP
      throughput:
        port: 6789
      inform:
        port: 8080
      gui:
        port: 8443
      http:
        port: 8880
      https:
        port: 8843
      discovery:
        port: 10001
        protocol: UDP

ingress:
  main:
    enabled: true
    className: "kong"
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      konghq.com/protocols: https
      konghq.com/https-redirect-status-code: "301"
    hosts:
      - host: &host unifi.suslian.engineer
        paths:
          - path: /
            service:
              name: main
              port: gui
    tls:
      - hosts:
          - *host
        secretName: unifi-tls

persistence:
  config:
    enabled: true
    type: persistentVolumeClaim
    accessMode: ReadWriteOnce
    size: 5Gi
    advancedMounts:
      main:
        main:
          - path: /usr/lib/unifi/data
