---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: buildkit-daemon-cert
spec:
  secretName: buildkit-daemon-certs
  duration: 8760h # 1 year
  renewBefore: 720h # 30 days
  commonName: buildkitd.default.svc
  dnsNames:
    - buildkitd.arc-system.svc
    - 127.0.0.1
  issuerRef:
    name: my-ca-issuer
    kind: Issuer
    group: cert-manager.io
  privateKey:
    algorithm: ECDSA
    size: 256
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: buildkit-client-cert
spec:
  secretName: buildkit-client-certs
  duration: 8760h # 1 year
  renewBefore: 720h # 30 days
  commonName: client
  issuerRef:
    name: my-ca-issuer
    kind: Issuer
    group: cert-manager.io
  privateKey:
    algorithm: ECDSA
    size: 256
  usages:
    - client auth
