---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mimir
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: mimir-distributed
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 5.8.0
    helm:
      valuesObject:
        ingester:
          extraEnvFrom:
            - configMapRef:
                name: s3-mimir
            - secretRef:
                name: s3-mimir
        store_gateway:
          extraEnvFrom:
            - configMapRef:
                name: s3-mimir
            - secretRef:
                name: s3-mimir
        querier:
          extraEnvFrom:
            - configMapRef:
                name: s3-mimir
            - secretRef:
                name: s3-mimir
        compactor:
          extraEnvFrom:
            - configMapRef:
                name: s3-mimir
            - secretRef:
                name: s3-mimir
        ruler:
          extraEnvFrom:
            - configMapRef:
                name: s3-mimir
            - secretRef:
                name: s3-mimir
        alertmanager:
          extraEnvFrom:
            - configMapRef:
                name: s3-mimir-misc
            - secretRef:
                name: s3-mimir-misc
        minio:
          enabled: false
        distributor:
          replicas: 2
        mimir:
          structuredConfig:
            common:
              storage:
                backend: s3
                s3:
                  endpoint: ${BUCKET_HOST}
                  bucket_name: mimir
                  insecure: true
            blocks_storage:
              backend: s3
              s3:
                endpoint: ${BUCKET_HOST}
                bucket_name: mimir
                insecure: true
            ruler_storage:
              backend: filesystem
              local:
                directory: /tmp/rules
            alertmanager_storage:
              backend: s3
              s3:
                endpoint: ${BUCKET_HOST}
                bucket_name: mimir-misc
                insecure: true
            limits:
              ingestion_rate: 100000
              ingestion_burst_size: 300000
              max_label_names_per_series: 60
              max_global_series_per_user: 0
              ruler_max_rules_per_rule_group: 0
              ruler_max_rule_groups_per_tenant: 0
              cardinality_analysis_enabled: true
  destination:
    name: in-cluster
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
