---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mimir
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: mimir-distributed
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 5.8.0
    helm:
      valuesObject:
        minio:
          enabled: false
        compactor:
          enabled: false
        distributor:
          replicas: 2
        store_gateway:
          enabled: false
        mimir:
          structuredConfig:
            common:
              storage:
                backend: filesystem
            blocks_storage:
              backend: filesystem
            limits:
              ingestion_rate: 100000
              ingestion_burst_size: 300000
              max_label_names_per_series: 60
              max_global_series_per_user: 0
              ruler_max_rules_per_rule_group: 0
              ruler_max_rule_groups_per_tenant: 0
              cardinality_analysis_enabled: true
  destination:
    name: in-cluster
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
