---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pyroscope
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - chart: pyroscope
      repoURL: https://grafana.github.io/helm-charts
      targetRevision: 1.15.0
      helm:
        valuesObject:
          alloy:
            enabled: false
          pyroscope:
            persistence:
              enabled: true
            podAnnotations:
              profiles.grafana.com/cpu.scrape: "false"
              profiles.grafana.com/memory.scrape: "false"
              profiles.grafana.com/goroutine.scrape: "false"
  destination:
    name: in-cluster
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
