controllers:
  main:
    pod:
      securityContext:
        fsGroup: 568
        fsGroupChangePolicy: "OnRootMismatch"

    containers:
      main:
        nameOverride: prowlarr
        image:
          repository: ghcr.io/onedr0p/prowlarr
          tag: 1.11.4
        env:
          TZ: "Europe/Paris"
        securityContext:
          runAsUser: 568
          runAsGroup: 568

service:
  main:
    ports:
      http:
        port: 9696

ingress:
  main:
    enabled: true
    className: "cilium"
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
    hosts:
      - host: &host prowlarr.suslian.engineer
        paths:
          - path: /
            service:
              name: main
              port: http
    tls:
      - hosts:
          - *host
        secretName: prowlarr-tls

persistence:
  config:
    enabled: true
    type: persistentVolumeClaim
    existingClaim: prowlarr-config
