apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: cert-manager
  project: default
  sources:
  - chart: cert-manager
    helm:
      valueFiles:
      - $values/k8s/sources/cert-manager/values.yaml
    repoURL: https://charts.jetstack.io
    targetRevision: v1.13.*
  - ref: values
    repoURL: https://github.com/synthe102/homelab.git
    targetRevision: main
  - path: k8s/sources/cert-manager/manifests
    repoURL: https://github.com/synthe102/homelab.git
    targetRevision: main
  syncPolicy:
    syncOptions:
    - PruneLast=true
    - CreateNamespace=true
    - ServerSideApply=true
