apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: prowlarr-vpn-config
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-auth-api
  target:
    name: prowlarr-vpn-config
  data:
    - secretKey: VPN_ENDPOINT_IP
      remoteRef:
        key: DOWNLOAD_VPN_ENDPOINT_IP
    - secretKey: WIREGUARD_ADDRESSES
      remoteRef:
        key: DOWNLOAD_WIREGUARD_ADDRESSES
    - secretKey: WIREGUARD_PRIVATE_KEY
      remoteRef:
        key: DOWNLOAD_WIREGUARD_PRIVATE_KEY
    - secretKey: WIREGUARD_PUBLIC_KEY
      remoteRef:
        key: DOWNLOAD_WIREGUARD_PUBLIC_KEY
