---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: falco
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - chart: falco
      repoURL: https://falcosecurity.github.io/charts
      targetRevision: 6.2.4
      helm:
        valuesObject:
          falco:
            webserver:
              prometheus_metrics_enabled: true
          collectors:
            kubernetes:
              enabled: true
          metrics:
            enabled: true
          serviceMonitor:
            create: true
          grafana:
            dashboards:
              enabled: true
  destination:
    name: in-cluster
    namespace: falco
  syncPolicy:
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: privileged
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
