---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: falco
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - chart: falco
      repoURL: https://falcosecurity.github.io/charts
      targetRevision: 6.3.0
      helm:
        valuesObject:
          falco:
            webserver:
              prometheus_metrics_enabled: true
          driver:
            kind: modern_ebpf
          falcosidekick:
            enabled: true
            serviceMonitor:
              enabled: true
            prometheusRules:
              enabled: true
            grafana:
              dashboards:
                enabled: true
            config:
              loki:
                hostport: http://loki-headless.monitoring.svc.cluster.local:3100
          tty: true
          collectors:
            kubernetes:
              enabled: true
          metrics:
            enabled: true
          serviceMonitor:
            create: true
          grafana:
            dashboards:
              enabled: true
  destination:
    name: in-cluster
    namespace: falco
  syncPolicy:
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: privileged
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
