---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: falco
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: 'https://github.com/synthe102/homelab.git'
      targetRevision: HEAD
      ref: values
    - chart: falco
      repoURL: https://falcosecurity.github.io/charts
      targetRevision: 7.0.2
      helm:
        valueFiles:
          - $values/clusters/k8s-01/apps/falco/values.yaml
  destination:
    name: in-cluster
    namespace: falco
  syncPolicy:
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: privileged
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
