apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mayastor
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: in-cluster
    namespace: mayastor
  project: default
  sources:
  - chart: mayastor
    helm:
      valueFiles:
      - $values/k8s/sources/mayastor/values.yaml
    repoURL: https://openebs.github.io/mayastor-extensions
    targetRevision: 2.8.*
  - ref: values
    repoURL: https://github.com/synthe102/homelab.git
    targetRevision: main
  - path: k8s/sources/mayastor/manifests
    repoURL: https://github.com/synthe102/homelab.git
    targetRevision: main
  syncPolicy:
    syncOptions:
    - PruneLast=true
    - CreateNamespace=true
