---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: immich
  namespace: immich
spec:
  backup:
    barmanObjectStore:
      wal:
        compression: bzip2
      data:
        compression: bzip2
      destinationPath: "s3://velero-backups-synthe/cnpg"
      s3Credentials:
        accessKeyId:
          name: aws-s3-creds
          key: AWS_ACCESS_KEY_ID
        secretAccessKey:
          name: aws-s3-creds
          key: AWS_SECRET_ACCESS_KEY
    retentionPolicy: "15d"
  instances: 1 
  enableSuperuserAccess: true
  bootstrap:
    initdb:
      database: immich
      postInitApplicationSQL:
        - ALTER SYSTEM SET search_path TO "$user", public, vectors;
        - SET search_path TO "$user", public, vectors;
        - CREATE EXTENSION IF NOT EXISTS "vectors";
        - CREATE EXTENSION IF NOT EXISTS "cube";
        - CREATE EXTENSION IF NOT EXISTS "earthdistance";
        - ALTER SCHEMA vectors OWNER TO "immich";
        - GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA vectors TO "immich";
        - GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO "immich";
      owner: immich
      secret:
        name: immich-db-user
      dataChecksums: true
      encoding: 'UTF8'
  storage:
    size: 8Gi
  imageName: ghcr.io/tensorchord/cloudnative-pgvecto.rs:16.3-v0.2.1
  resources:
    requests:
      memory: "512Mi"
    limits:
      hugepages-2Mi: "512Mi"
  postgresql:
    enableAlterSystem: true
    parameters:
      shared_buffers: "128MB"
    shared_preload_libraries: # load pgvecto.rs shared library
    - "vectors.so"
