apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: aws-s3-creds
  namespace: immich
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-auth-api
  target:
    name: aws-s3-creds
  data:
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: VELERO_ACCESS_KEY_ID
        metadataPolicy: None
      secretKey: AWS_ACCESS_KEY_ID
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: VELERO_SECRET_ACCESS_KEY
        metadataPolicy: None
      secretKey: AWS_SECRET_ACCESS_KEY
