apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: unpoller
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-homelab
    kind: ClusterSecretStore
  dataFrom:
    - extract:
        key: K8S_01_KUBE_MONITORING_UNIFIPOLLER
