---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: zigbee2mqtt
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: in-cluster
    namespace: home-automation
  project: default
  sources:
    - repoURL: https://bjw-s-labs.github.io/helm-charts
      targetRevision: 4.0.1
      chart: app-template
      helm:
        valuesObject:
          controllers:
            main:
              containers:
                main:
                  env:
                    ZIGBEE2MQTT_CONFIG_SERIAL_PORT: tcp://xzg.iot.suslian.engineer:6638
                    ZIGBEE2MQTT_CONFIG_MQTT_SERVER: mqtt://mosquitto.home-automation.svc.cluster.local
                    ZIGBEE2MQTT_CONFIG_HOMEASSISTANT_ENABLED: true
                    ZIGBEE2MQTT_CONFIG_HOMEASSISTANT_DISCOVERY_TOPIC: homeassistant
                    ZIGBEE2MQTT_CONFIG_HOMEASSISTANT_STATUS_TOPIC: homeassistant/status
                  image:
                    repository: ghcr.io/koenkk/zigbee2mqtt
                    tag: 2.4.0
          service:
            main:
              ports:
                http:
                  port: 8080
          ingress:
            main:
              enabled: true
              className: "kong"
              annotations:
                cert-manager.io/cluster-issuer: letsencrypt-prod
                konghq.com/protocols: https
                konghq.com/https-redirect-status-code: "301"
              hosts:
                - host: &host z2m.iot.suslian.engineer
                  paths:
                    - path: /
                      service:
                        identifier: main
                        port: http
              tls:
                - hosts:
                    - *host
                  secretName: zigbee2mqtt-tls
          persistence:
            data:
              enabled: true
              type: persistentVolumeClaim
              accessMode: ReadWriteOnce
              size: 5Gi
              globalMounts:
                - path: /app/data
    - path: clusters/k8s-01/apps/home-automation/zigbee2mqtt/configs
      repoURL: 'https://github.com/synthe102/homelab.git'
      targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
