---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: forgejo
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: in-cluster
    namespace: forgejo
  project: default
  sources:
    - chart: forgejo
      repoURL: code.forgejo.org/forgejo-helm
      targetRevision: 15.0.3
      helm:
        valuesObject:
          httpRoute:
            enabled: true
            hostnames:
              - git.volcan.cloud
            parentRefs:
              - name: internal
                namespace: kube-system
                sectionName: https-volcan
          gitea:
            config:
              server:
                ROOT_URL: https://git.volcan.cloud
          service:
            ssh:
              type: LoadBalancer
              annotations:
                lbipam.cilium.io/sharing-key: "internal"
                lbipam.cilium.io/sharing-cross-namespace: "*"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
