apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflare-api-token
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-auth-api
  target:
    name: cloudflare-api-token
  data:
    - secretKey: api-token
      remoteRef:
        key: CERT_MANAGER_CLOUDFLARE_API_TOKEN
