apiVersion: "cilium.io/v2alpha1"
kind: CiliumL2AnnouncementPolicy
metadata:
  name: lb
spec:
  nodeSelector:
    matchExpressions:
      - key: node-role.kubernetes.io/control-plane
        operator: In 
        values:
          - "true"
  interfaces:
  - eno1
  externalIPs: true
  loadBalancerIPs: true
