---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: &name authentik
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: 'https://github.com/synthe102/homelab.git'
      targetRevision: HEAD
      ref: values
    - chart: authentik
      helm:
        valueFiles:
          - $values/clusters/k8s-01/apps/authentik/values.yaml
      repoURL: https://charts.goauthentik.io/
      targetRevision: 2025.10.3
    - path: clusters/k8s-01/apps/authentik/configs
      repoURL: 'https://github.com/synthe102/homelab.git'
      targetRevision: HEAD
  destination:
    name: in-cluster
    namespace: *name 
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
