apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kong
  namespace: argocd
spec:
  project: default
  ignoreDifferences:
  - kind: Secret
    jsonPointers:
    - /data/ca.crt
    - /data/ca.key
    - /data/tls.crt
    - /data/tls.key
  source:
    chart: ingress
    repoURL: https://charts.konghq.com
    targetRevision: 0.18.0
  destination:
    name: in-cluster
    namespace: kong
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
