---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gha-runner-scale-set-controller
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  ignoreDifferences:
    - kind: CustomResourceDefinition
      group: apiextensions.k8s.io
      jsonPointers:
        - /spec/preserveUnknownFields
  sources:
    - chart: gha-runner-scale-set-controller
      repoURL: ghcr.io/actions/actions-runner-controller-charts
      targetRevision: 0.11.0
  destination:
    name: in-cluster
    namespace: arc-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: privileged
    syncOptions:
      - CreateNamespace=true
