---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tuppr
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - chart: tuppr
      repoURL: ghcr.io/home-operations/charts
      targetRevision: 0.5.3
      helm:
        releaseName: tuppr
        valueFiles:
          - $values/clusters/k8s-01/apps/system-upgrade/app/values.yaml
    - repoURL: 'https://github.com/synthe102/homelab.git'
      targetRevision: HEAD
      ref: values
  destination:
    name: in-cluster
    namespace: system-upgrade
  ignoreDifferences:
    # tuppr generates and rotates its own webhook certificates.
    - group: ""
      kind: Secret
      name: tuppr-webhook-server-cert
      namespace: system-upgrade
      jsonPointers:
        - /data
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      name: tuppr-validating-webhook
      jqPathExpressions:
        - .webhooks[].clientConfig.caBundle
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: privileged
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
