---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: &app system-upgrade-controller
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: 'https://github.com/synthe102/homelab.git'
      targetRevision: HEAD
      ref: values
    - chart: app-template
      repoURL: https://bjw-s-labs.github.io/helm-charts
      targetRevision: 4.5.0
      helm:
        valueFiles:
          - $values/clusters/k8s-01/apps/system-upgrade/app/values.yaml
    - path: clusters/k8s-01/apps/system-upgrade/app/rbac
      repoURL: 'https://github.com/synthe102/homelab.git'
      targetRevision: HEAD
  destination:
    name: in-cluster
    namespace: system-upgrade
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: privileged
    syncOptions:
      - CreateNamespace=true
