global:
  logging:
    format: json
    level: warn
configs:
  params:
    server.insecure: true #required with cilium ingress right now
  cm:
    # Disable the admin user, only allows GitHub users to login
    admin.enabled: "true"
    # Allows logs and shells
    # exec.enabled: "true"
    # Allow display of statusbadge
    statusbadge.enabled: "true"
    #Url of the server, required for the GitHub auth
    # url: 'https://argo.suslian.engineer'
    # dex.config: |
    #   connectors:
    #     #GitHub
    #     - type: github
    #       id: github
    #       name: GitHub
    #       config:
    #         clientID: 8849c4478dc3afa63a4b
    #         clientSecret: $dex.github.clientSecret
    # Disable diff check for caBundles on mutating webhooks (because they are generated on a per-installation basis)
    resource.customizations.ignoreDifferences.admissionregistration.k8s.io_MutatingWebhookConfiguration: |
      jqPathExpressions:
      - '.webhooks[]?.clientConfig.caBundle'
    # Disable updates for certificates authorities in secrets
    resource.customizations.ignoreDifferences.Secret: |
      jqPathExpressions:
      - '.data."ca.crt"'
      - '.data."ca.key"'
      - '.data."tls.key"'
      - '.data."tls.crt"'
      - '.data."jwt-token.pem"'
    resource.compareoptions: |
      # disables status field diffing in specified resource types
      # 'crd' - CustomResourceDefinition-s (default)
      # 'all' - all resources
      # 'none' - disabled
      ignoreResourceStatusField: crd
  # rbac:
  #   policy.default: role:readonly
  #   policy.csv: |
  #     g, synthe102, role:admin
  #   scopes: '[groups, preferred_username]'
server:
  ingress:
    enabled: true
    ingressClassName: "cilium"
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
    hosts:
      - argo.suslian.engineer
    tls:
      - hosts:
          - argo.suslian.engineer
        secretName: argocd-tls
    https: false
