---
name: Argo CD Diff Preview
on:
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: gha-runner-synthe102-homelab
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          path: pull-request
          persist-credentials: false
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          ref: main
          path: main
          persist-credentials: false
      - name: Install GH cli
        run: |
          (type -p wget >/dev/null || (sudo apt update && sudo apt-get install wget -y)) \
          && sudo mkdir -p -m 755 /etc/apt/keyrings \
                && out=$(mktemp) && wget -nv -O$out https://cli.github.com/packages/githubcli-archive-keyring.gpg \
                && cat $out | sudo tee /etc/apt/keyrings/githubcli-archive-keyring.gpg > /dev/null \
          && sudo chmod go+r /etc/apt/keyrings/githubcli-archive-keyring.gpg \
          && echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
          && sudo apt update \
          && sudo apt install gh -y
      - name: Generate Diff
        env:
          # renovate: datasource=docker depName=dagandersen/argocd-diff-preview
          ARGOCD_DIFF_PREVIEW_VERSION: v0.2.11
          TARGET_BRANCH: ${{ github.head_ref }}
          REPO: ${{ github.repository }}
        run: |
          docker run \
            --network=host \
            -v /var/run/docker.sock:/var/run/docker.sock \
            -v $(pwd)/main:/base-branch \
            -v $(pwd)/pull-request:/target-branch \
            -v $(pwd)/output:/output \
            -e TARGET_BRANCH \
            -e REPO \
            dagandersen/argocd-diff-preview:${ARGOCD_DIFF_PREVIEW_VERSION} \
            --kind-options '--config /base-branch/.github/hack/kind.yaml' \
            --diff-ignore '([a-z0-9]{5}-[bt]-[a-z]|checksum/(secret|init-config):)'
      - name: Post diff as comment
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.number }}
          REPO: ${{ github.repository }}
        run: |
          gh pr comment "${PR_NUMBER}" --repo "${REPO}" --body-file output/diff.md --edit-last || \
          gh pr comment "${PR_NUMBER}" --repo "${REPO}" --body-file output/diff.md
