---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: gateway-tls
  namespace: kube-system
spec:
  dnsNames:
    - '*.suslian.engineer'
    - '*.k8s-01.suslian.engineer'
    - '*.iot.suslian.engineer'
    - '*.s3.k8s-01.suslian.engineer'
    - '*.volcan.cloud'
    - '*.mc.volcan.cloud'
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-prod
  secretName: gateway-tls
  usages:
    - digital signature
    - key encipherment
