apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
  - chart: cert-manager
    repoURL: https://charts.jetstack.io
    targetRevision: v1.17.1
    helm:
      valuesObject:
        crds:
          enabled: true
  - path: clusters/k8s-01/apps/cert-manager/configs
    repoURL: 'https://github.com/synthe102/homelab.git'
    targetRevision: HEAD
  destination:
    name: in-cluster
    namespace: cert-manager
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
